### ISSUE TITLE
[FEATURE] Remember the last location

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#1]
When adding folders with mods, each time the program returns to "Quick Access" instead of staying in the last folder from which the folder with mods was loaded. With adding 10+ such folders it is a bit of a pain to enter the same location every time.

**Comment by FSGModding** [comment]
As in the "hit the add folder button", and it defaults back to (i think) your documents folder?  or maybe the games folder?  Pretty sure I know where you mean, I can address that to remember the last for as long as the program is open

**Comment by KITT3000** [comment]
Nope, it start always in `C:\Users\USER_NAME`

**Comment by jtsage** [comment]
Gotcha.  Yeah I wasn't sure what I provided as a default, but I do remember having to provide something.  I'll set it up so that the default for every subsequent add is whatever folder you just added, up one parent.  (so c:\mods\somefolder -> c:\mods)
