### ISSUE TITLE
[BUG] Javascript Unhandled/Uncaught Exception Error

### ISSUE THREAD

**Issue by BurcoGames** [FSGModding/FSG_Mod_Assistant#10]
When clicking the "3 dots" button next to the "Launch FS2022" button, a Javascript unhandled exception occurs. Clearing the error popup lets the program work normally, except that the bottom half of the settings screen has no text. Exiting the preferences screen and re-opening it reproduces the popup.

Attached to this report are the screencaps of what I see when this occurs.

![Screenshot 2022-11-05 142048](https://user-images.githubusercontent.com/85097345/200137513-14a1076a-999c-428f-a001-9a832a1d89ed.png)
![Screenshot 2022-11-05 142619](https://user-images.githubusercontent.com/85097345/200137515-6f567e3a-f22f-498d-a9e8-654f9e2b114b.png)

**Comment by jtsage** [comment]
ooooh.  you opened preferences before adding any folders I think?  I had not thought to try that. Because of course the cache file wouldn't exist before there were mods *to* cache.  This is a great catch, thank you - i'll push a fix for this in the next couple of days for sure.

**Comment by BurcoGames** [comment]
Yeah, just tested that now with actually having folders in and the error didn't re-appear, so it seems to only be without folders. Lucky me to find it, I guess!

**Comment by PappaBeerNL** [comment]
I got this error msg at first start

**Comment by jtsage** [comment]
Technically fixed in 1.0.1, really fixed in 1.1.0 in a few days.
