### ISSUE TITLE
[BUG] Crash on Game Launch

### ISSUE THREAD

**Issue by Farmer17** [FSGModding/FSG_Mod_Assistant#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My FS22 launch button keeps getting an error. I get a separate screen that exits out of the Mod Assistant. I would copy or take a pic but it will not let me.

### Environment

```markdown
- Mod Assistant Version:2.1.4
- OS: windows 11
- Virtualized: no
```

**Comment by jtsage** [comment]
So, there is a `crash.log` file that is created in `C:\Users\[YOUR USERNAME HERE]\AppData\Roaming\fsg-mod-assistant` - also of use would be `assist.log` from when that happened.  But without those log files, it is all but impossible for me to track down what might be happening.

**Comment by Farmer17** [comment]
Ok
I will check on that. Thank you for getting back so quick.
