### ISSUE TITLE
[FEATURE] Savegame support

### ISSUE THREAD

**Issue by Nathan-Shea** [FSGModding/FSG_Mod_Assistant#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The ability to also change the savegame folder along with the mods folder.

### Anything else?

Apologies if this is covered by #24

**Comment by jtsage** [comment]
It is indeed basically covered with #24 - you *can* move the location of the savegames - a symlink would be the easier way, or you can actually mess with your windows configuration enough for it to store <user>/Documents/ somewhere other than the default.  The first method is not something I can make mod assistant do without admin access (and it's all or nothing, there is no way for electron to "elevate" itself for only those operations - and I don't want the assistant running as admin full-time - that's just asking for bad stuff to happen).  The second method is way outside of the scope of what this program wants to be - and I suspect it would also need admin access.

Sorry bout that.  Closing as not-possible. :)
