### ISSUE TITLE
[BUG] ModAssistant 2.2.2 Crashes on Startup 

### ISSUE THREAD

**Issue by ScootersWorkbench** [FSGModding/FSG_Mod_Assistant#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting the app,  the new mod refresh screen displays and counts all mods,  then displays an unhandled Exception box 4 times and closes.      
![image](https://user-images.githubusercontent.com/75384460/234366221-c1770298-eda1-4483-8518-937cfd9fbadf.png)
[crash.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/11325610/crash.log)

I have attached the screen shot and the crash.log file.

### Environment

```markdown
- Mod Assistant Version: 2.2.2
- OS: Windows 10
- Virtualized: no
```

**Comment by jtsage** [comment]
huh.  that one is new.  probably an easy fix, and I owe a version drop today anyway.  give me a few hours to duplicate

**Comment by ScootersWorkbench** [comment]
Thanks man.   No problem.  Just thought you'd want to know.

**Comment by jtsage** [comment]
so, it's a bad mod.  this in a modDesc.xml will do it

`<iconFilename><stuff>a.dds</stuff></iconFilename>`  (empty or missing is fine though)

At any rate, it shouldn't crash when it happens though

**Comment by ScootersWorkbench** [comment]
Dang,  I figured it was a mod.   Just don't remember what I added lately.  LOL.

**Comment by jtsage** [comment]
Fwiw, I left that error message in the log - and of course, it's gonna fail to load the icon file, so look for the ones that are missing :)

**Comment by ScootersWorkbench** [comment]
Downloaded and verified the 2.2.3 and the issue is resolved.   Thanks for the quick turnaround!
