### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FlyingMasterChef** [FSGModding/FSG_Mod_Assistant#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I do anything in the app it checks EVERY mod again. I have the ONEDRIVE sync mode turned off. Never turned it on, actually.  Yet it refreshes on every action.  If I copy a mod to another folder, move a mod, etc...  

### Expected Behavior

Check ALL the mods once and then never again unless refresh all is chosen.  Only check mods in the folder that a mod was dropped into. But even then, why verify the mod when it's been verified and checked? Why not just update the file system?

### Steps To Reproduce

Just copy any mod from one folder to another. 

### Environment

```markdown
- Mod Assistant Version: 2.2.3
- OS: Windows 11 Pro (newest version always)
- Virtualized: NO
```

### Anything else?

Since I have moved my 40 favorites to every map folder I am well over 1400 mods now.  And I have not even put NON favorite mods in the map folders yet.  As I have averaged what I use per map I am going to be over 13,000 mods that it will check EVERY time I do anything in the app.  For example, every time I copy a mod from the ALL MODS folder to a map folder it will scan NOT just the map folder but every mod in every folder.  Just before posting this I was waiting 3 minutes for it to complete a scan and I still have to move 23 map files into their own folders. That's going to be over an hour of waiting just because I need to copy one file into each map folder. UGH!

I have cleaned the cache and Cleared the cache to see if that would fix it. It did not.

**Comment by jtsage** [comment]
Did you try it with the sync mode turned on?  Mod Assitant looks at the file name, location, size,  and *last modified* time to decide if the mod is "new" or not - **any** drive sync program can mess with the last modified time, so the "one drive mode" tells mod assistant to use the *creation time* of the file instead - by doing this however, it is possible (although unlikely) that an update will be missed.

**Comment by FlyingMasterChef** [comment]
I will try it with that...but as I read the instructions, like you stated, it will most likely MISS updates with this turned on.  Sort of a bummer to lose that great feature.  

On a side note, I do very much wish the decision to NOT use Hard LInks instead of direct copying will be re-looked at.  At least the option so users can decide to use them or not.  I am currently wasting literally 240+ gigs of space because of all the duplicate files.  UGH!  :)

Greg
