### ISSUE TITLE
[BUG] - Mod Update Version Comparison

### ISSUE THREAD

**Issue by Ulanawius** [FSGModding/FSG_Mod_Assistant#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Thank you very much for the great work! I'm using this now always to manage my mods.
 Today I found the following behaviour:
A mod is updated with version 1.10.0.0. During the comparison with the older mod versions FSG thinks, that the earlier version 1.9.0.0 of this mod is newer version and wants to replace the just updated one - see screenshot.

![image](https://user-images.githubusercontent.com/76711921/236640459-4b00cb8b-65fb-4294-a329-83127e76c4a6.png)

### Expected Behavior

FSG should handle version 1.10.0.0 as newer.

### Steps To Reproduce

LS22 with mod "FS22_aPalletAutoLoader"

### Environment

```markdown
- Mod Assistant Version: 2.2.3
- OS: Win 10
- Virtualized: No
```

**Comment by jtsage** [comment]
Gross. Why in the world they couldn't have used real SemVer for versions is beyond me - look for this to be fixed in the next update, likely tomorrow.

**Comment by jtsage** [comment]
This will be in the release later tonight. I forgot to convert the string back to numbers prior to comparing.  Because text "10" is less than "9".  sigh.
