### ISSUE TITLE
[BUG]Can't launch game

### ISSUE THREAD

**Issue by drizz786** [FSGModding/FSG_Mod_Assistant#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After setting file paths, the launch game button results in an Error spawn , message and program closes.
[crash.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/11431704/crash.log)

### Expected Behavior

Game launch.

### Steps To Reproduce

Using installed version .
click short cut, assign folder paths, click launch game error msg shows and aprogram closes.
Game will run fine from the main short cut and use proper folder (set in MA) 

### Environment

```markdown
- Mod Assistant Version: 2.2.3
- OS: Win 10 pro 64bit
- Virtualized: no

Ryzen 3900x, PBO on / board limits 
16 gig 3600 cl 18 ram 2x8  slots  2, 4   
Arc A 770 16gig 
Samsung 960 pro 256 nvme  os drive  documents on 2 TB spinner 
FS22 1.91
```

### Anything else?

Awesome program thankyou.

**Comment by jtsage** [comment]
Which version of the game do you have?  Steam, Giant's Eshop, something else?  Your crash log shows it trying (and failing) to run `C:\Program Files (x86)\Farming Simulator 2022\FarmingSimulator2022.exe` 

I'm going to add some logic around this to not crash, but an update would be helpful to track this down

**Comment by drizz786** [comment]
Hi, sorry for delay, i have the Giants shop pre order  version .
Easier to swap files about. Thanks for the quick reply. Greg aka drizz786.

**Comment by jtsage** [comment]
Added a bunch more error trapping, hopefully that clears this up.
