### ISSUE TITLE
Is it possible to add ignoring the display of such 'Errors'? [FEATURE]

### ISSUE THREAD

**Issue by vitalii2011** [FSGModding/FSG_Mod_Assistant#118]
FS19 will never be loaded again, but mods from it are still being looked at (for reference, etc.).
- Is it possible to add the "Ignore this": 
![0010](https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/87e9a2d2-854f-4662-856e-b25590e3a759)

![0011](https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/1c7f23d7-c93e-460e-a21d-9fc4eaeaebd9)
 item to the context menu, by right-clicking the mouse?

**Comment by jtsage** [comment]
Hmm.  let me think some more on this, but I can at least have the little flag cleared when you open the debug log.
