### ISSUE TITLE
Button name "Refresh" is not visible behind window controls[BUG]

### ISSUE THREAD

**Issue by vitalii2011** [FSGModding/FSG_Mod_Assistant#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Mod Assistant Version: 2.4.0
- OS: w10
- Virtualized:
```

**Comment by vitalii2011** [comment]
![0010](https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/849d98d3-eddf-42ce-a890-8fe1bf7ea2cb)

**Comment by vitalii2011** [comment]
If possible, I'll ask here: Crop Calendar is not implemented yet? Why is this in FSModAssistant? )

**Comment by jtsage** [comment]
> If possible, I'll ask here: Crop Calendar is not implemented yet? Why is this in FSModAssistant? )

Pull up a detail window of a map (double click), and scroll down. It should be right below the description (moddesc) stuff. I should have done a better announcement

Fwiw, I didn't send it to crowdin, but I did grab the month names and the crop names direct from the game files for all current translations

**Comment by vitalii2011** [comment]
- Clearly, I'm developing a vanilla map and I don't have any mod maps.
- I have already translated months and crops on Crowdin. ) They are quite a bit different from those accepted in the game: for several months in Russian they are not reduced to three letters and somewhere added "ё".

**Comment by jtsage** [comment]
## Crop Calendar Example
![2023-06-11 08_43_18-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/7a4389a2-7a23-40a1-a7a5-cc9a28b6dbfd)

## Refresh Button Tooltip fixed
![2023-06-11 08_45_25-debug html - FSG_Mod_Assistant - Visual Studio Code](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/fa18a030-7541-49ba-a87c-e76043c22c97)

**Comment by vitalii2011** [comment]
Between July and October there are two Septembers (in Russian and English): 
![Image 001](https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/294e11fe-ff2c-4c33-884b-e9fe9973ee95)

**Comment by jtsage** [comment]
OH!  ok, took a bit - but it's not a duplicate exactly, it was a poor job of copy-paste.  I set the translation of AUG to the word for September, and then failed to copy over September at all.  This is already fixed upstream when I run the next build.

![2023-06-11 12_52_07-Update translations from crowdin  Re_ #127 also  · FSGModding_FSG_Mod_Assistant@](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/ff9a3f39-4a2b-4f1b-bfb0-51ff51c01125)

**Comment by jtsage** [comment]
Closing these as complete, i'm sure there will be more soon.  The "look inside the mod" feature is pretty cool, and bound to throw all sorts of issues around.
