### ISSUE TITLE
[BUG] FSGMA Crashes on run against fresh install of FS22 (Steam Edition) if it is run before FS22's First Run

### ISSUE THREAD

**Issue by Dylan-M** [FSGModding/FSG_Mod_Assistant#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you perform a fresh install of FS22 on a clean system (I got a new gaming laptop for when I'm on the road, w00t!), and then run FSG Mod Assistant **BEFORE** running FS22, you will get the error in the attached screenshot and Mod Assistant crashes.
![Screenshot 2023-06-10 232039](https://github.com/FSGModding/FSG_Mod_Assistant/assets/545408/f933972d-6b24-49a7-99f7-2a239f4bcc4c)

### Expected Behavior

Mod Assistant displays a message about what happened, why, and offers a suggestion on how to remediate it. It should also offer an exit button for a clean exit.

### Steps To Reproduce

1. Start with a brand new system, or uninstall FS22 and delete the files game.xml and gameSettings.xml from your Docs/My Games/FS22 directory (that is a pseudo directory, but JTSage knows)
2. Run FSG Mod Assistant
3. See crash, as in the screenshot above

### Environment

```markdown
- Mod Assistant Version: 2.5.0
- OS: Win11
- Virtualized: No
```

**Comment by jtsage** [comment]
I think I found out where this is happening - bit wore out for the evening, I'll give it a test tomorrow.  I expect another version build before this weekend, there was a bunch of other stuff that hit today too :)

**Comment by jtsage** [comment]
Gonna close as complete with 2.6.0, but please reopen if it's still a thing.
