### ISSUE TITLE
[BUG] After upgrading from v2.2.3 to v2.6.0 the program crashes

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I haven't used the program for a long time and missed some updates, today I started it, the program checked the mod collections and the update popped up. It was done and when checking the files again there was an error with ss, now every time I start the program I get the same error.

### Environment

```markdown
- Mod Assistant Version: v2.6.0
- OS: Win 10
- Virtualized: No
- Game Version: Steam and Giants E-Shop
```

### Anything else?

![image](https://github.com/FSGModding/FSG_Mod_Assistant/assets/2678653/c0deaa41-c72f-483d-82c3-699a01246005)
[crash.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/11779005/crash.log)

**Comment by jtsage** [comment]
Well that's not supposed to happen.  Let me get a patch out for this in the next couple hours.

**Comment by KITT3000** [comment]
In v2.6.1 working ok.
