### ISSUE TITLE
[FEATURE] 'Dev' log entries

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I have the `-devWarnings` and `-scriptDebug` commands turned on, it would be good if they were recognized separately in the game LOG checking window (apart from the default "warnings" and "error/error lua") additionally the `CollisionFlag-Check:` entry should be colored on red.

### Anything else?

I am attaching the LOG file for analysis.
[log.txt](https://github.com/FSGModding/FSG_Mod_Assistant/files/11859960/log.txt)

**Comment by jtsage** [comment]
Huh. Cool. I admit, I didn't know any of those options existed. Yeah, I can add some additional colors and filtering for the output.

**Comment by jtsage** [comment]
Thanks for the sample log, that saved a ton of time.  2 filters added, "DEV INFO" and "DEV WARNING".  The colliison flag I put into errors.

## Difference between WARNING and DEV WARNING
![2023-07-01 21_44_01-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/30921e64-a7c5-46d0-a97f-0ec003e09405)

## Difference between INFO and DEV INFO
![2023-07-01 21_44_11-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/88e73b33-a272-4167-a3ba-0bb95c236680)

## Collision Flag ERROR
![2023-07-01 21_44_19-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/939b5e58-c583-4c76-8931-aedf4e2e2254)
