### ISSUE TITLE
[FEATURE] Offline Storage

### ISSUE THREAD

**Issue by AZSparky** [FSGModding/FSG_Mod_Assistant#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

So there I was.  Trying to become an organized nerd gaming Sailor while stationed on my ship and gaming on my shiny new laptop gaming rig.  I decided to use an SSD I had in my old laptop and pop it into an external enclosure (since my new rig only has one SSD slot).  BOOM with my new 1TB external SSD I could now move so many games to this drive to have them available when I want, of course keeping my beloved FS22 on my internal drive.

As I was freeing up storage on my internal drive by moving them to my new external, I saw about 400GB of mods I've been hording in multiple folders using this lovely mod assistant, so I had an epiphany and decided to move them to my external!!! SO MUCH FREE SPACE!!!!! However when I launch Mod Assistant with my external not attached, it removes them and I have to re add them once I plug the external back in.  I know, First World Problems right!  Right now as long as I ensure that I plug the external in prior to launching, no issues

### Describe the solution you'd like

It would be helpful to allow specific collections to remain in the Mod Assistant even when the drive is unplugged so that the order and organization isn't lost once setup.

### Anything else?

Hopefully you enjoyed my story!!!

**Comment by jtsage** [comment]
![2023-07-01 21_13_59-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/ae4bfaa0-aa68-4e23-9794-7ac1c01e7849)

So, this option is off by default - and when off, works the same way things do now - a missing collection folder is assumed to be invalid, and is removed from mod assistant.

When toggled on, if the collection is offline, it will be skipped in Mod Assistant - it will not appear in the collection list or the folder list - however, if you plug the drive back in and hit reload, it will auto-magically reappear.

**Comment by AZSparky** [comment]
You're a real American hero
