### ISSUE TITLE
Feature request active date 

### ISSUE THREAD

**Issue by judg393** [FSGModding/FSG_Mod_Assistant#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

So we all know mod conflicts can be a pain in the neck to help narrow down conflicts created by recently added mods 

### Describe the solution you'd like

I wonder if it’s possible to record some Where some how the date and time a mod was activated so you can then see easily which mods were added recently. 

I know it shows recently added to MA but I wonder if it’s possible to record when it was activated in a save?

**Comment by jtsage** [comment]
That's a good question - I do not know off the top of my head that FS tracks that sort of info.  And if your operating system is behaving how it's supposed to, file date on the mods would not be useful either.  What might be doable is checking for the existence of savegame backups for the savegame you are comparing with, and taking an educated guess as to *about* when the mod was added.

At any rate, I like the idea, and will spend some time running down what might be possible.

**Comment by jtsage** [comment]
Update:

1.) In no way is the add date stored in the savegame file - it neither knows nor cares.

2.) I *could* parse the savegame backups to compare which mods are activated.  I think it would be best as sort of a standalone feature, because of course it can't work with downloaded MP saves.  But local ones are a possibility.

**Comment by jtsage** [comment]
![2023-07-03 20_59_46-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/73e457cf-02fe-45d6-84da-9bed25167c57)


![2023-07-03 20_59_59-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/ebfc7a09-9d54-4ad1-8722-f97f296a3f64)


![2023-07-03 21_00_08-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/4d5c751d-0148-4427-add1-d5cbde133e08)


![2023-07-03 21_00_23-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/600d73e7-db69-4577-94b7-20038eb8e979)
