### ISSUE TITLE
[BUG] Changing gameSettings.xml path does not update the original file and therefore loads wrong settings

### ISSUE THREAD

**Issue by kman3107** [FSGModding/FSG_Mod_Assistant#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use FSG Mod Assistant without changing the default location of the gameSettings.xml file I have no issues, but when I change the default location (in this instance the parent directory of the place I store my mod folders) it updates the "new" gameSettings.xml file, but doesn't update the gameSettings.xml file in C:\Users\<user>\Documents\My Games\FarmingSimulator2022

### Expected Behavior

Expect the gameSettings.xml file in C:\Users\<user>\Documents\My Games\FarmingSimulator2022 to be ignored, or updated when I change(I mean when I change the active mod folder) the gameSettings.xml I have set in the User Preferences of the FSG Mod Assistant application.

### Steps To Reproduce

1. Set active collection <Collection 1>
2. Copy gameSettings.xml from C:\Users\<user>\Documents\My Games\FarmingSimulator2022 to F:\FS22Mods
3. In User Preferences, set default location for the gameSettings.xml file to F:\FS22Mods
4. Launch game and everything works
5. Exit game
6. Change active collection to <Collection 2>
7. Launch game and find that <Collection 1> is still the one loaded
8. Check C:\Users\<user>\Documents\My Games\FarmingSimulator2022\gameSettings.xml and find it is still has <Collection 1>
9. Check F:\FS22Mods\gameSettings.xml and find it has <Collection 2>
10. Try to Clean Cache, Clear Cache, and restart FSG Mod Assistant
11. Still not working as intended

### Environment

```markdown
- Mod Assistant Version: 2.8.2
- OS: Windows 10 - build: 19044.3086
- Virtualized: No
- Game Version: Steam
```

**Comment by jtsage** [comment]
I don't think I understand at all - why are you changing the location of gameSettings.xml per-collection?  That is the file farm sim reads, and it expects it to be in the same place every time.

What you've described is exactly how MA is meant to function - you've made a copy of the gameSettings.xml file and told MA to update that copy - but it no longer knows or cares about the original, and Farm Sim is only going to look at the original.

**Comment by kman3107** [comment]
> I don't think I understand at all - why are you changing the location of gameSettings.xml per-collection?

I do NOT set gameSettings.xml per-collection.



> What you've described is exactly how MA is meant to function - you've made a copy of the gameSettings.xml file and told MA to update that copy - but it no longer knows or cares about the original, and Farm Sim is only going to look at the original.

So you are saying that I'm only pointing MA to another file, I'm not changing where the game perceives the file to be?
If this is the case then I have not understood the function of setting the location of the gameSettings.xml file.
This is my bad then. Confirm this and I will close the issue.

**Comment by jtsage** [comment]
> So you are saying that I'm only pointing MA to another file, I'm not changing where the game perceives the file to be?
> If this is the case then I have not understood the function of setting the location of the gameSettings.xml file.
> This is my bad then. Confirm this and I will close the issue.

The use of setting the location of the `gameSettings.xml` file is because once in a while, on some machines, MA will be unable to find it for whatever reason.  This mostly happens when somebody used oneDrive for a while, and then stopped, and now there is a copy of `Documents/My Games/...` under both their current home folder, and the old oneDrive one (or vice versa).

So, yes, the `gameSettings.xml` MA should be pointed at is whichever one is in the folder when you open explorer -> `Documents` -> `My Games` -> `Farming Simulator 2022` - that's the one the game will read.

**Comment by kman3107** [comment]
Thank you @jtsage 
I am always looking for ways to keep the settings of games and programs safe on something other than the OS drive, since sometimes you get unlucky and need a new OS install, and sometimes you aren't able to access the files on the old OS.

Guess my wishful thinking blinded me to the truth here. Thanks for the explanation as well.
Have a good one o/

**Comment by jtsage** [comment]
Sure thing.  I was just talking to another about this, as the question of "how can I move the `Documents\My Games\FarmingSimultor2022` folder somewhere else" has come up before - to the best of both out knowledge, you can't really.  Have a good one too!
