### ISSUE TITLE
Two line text does not fit on the "Show in Explorer" button [BUG]

### ISSUE THREAD

**Issue by vitalii2011** [FSGModding/FSG_Mod_Assistant#15]
**Describe the bug**
In the title.

**Screenshots**
![Image 002](https://user-images.githubusercontent.com/41552153/202593477-c83f5e82-b142-4ac7-bff6-1a9f11dbf109.png)
![Image 003](https://user-images.githubusercontent.com/41552153/202593480-3c02b43a-38cd-4984-a7d3-fae873c1dd91.png)
![Image 004](https://user-images.githubusercontent.com/41552153/202593482-32784eb8-6a49-40b7-a3d1-bb56a6eeae68.png)

**Desktop (please complete the following information):**
Windows 10

**Comment by jtsage** [comment]
I'm honestly surprised the other stuff works as well as it does.  I'll spend some time tweaking visuals when using some of the other locales, thanks!

**Comment by jtsage** [comment]
![2022-11-17 23_07_34-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/202614641-95b16b61-df92-4e44-a4a0-4de3c2cdc46b.png)

I messed with the button height on the top too so they are equal heights.
