### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by will630** [FSGModding/FSG_Mod_Assistant#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just had. an auto update to 3.0 and now I cannot see.my folders in mod assistant 

### Environment

```markdown
- Mod Assistant Version:
- OS:
- Virtualized:
```

**Comment by jtsage** [comment]
Once in a while, it seems that the mod assistant loses itself a little.  I *think* this was actually a bug in 2.9, and the update just was coincidental.  At any rate, you just need to re-add the folders.  All the cached mods and details should still be saved.  Sorry about that.
