### ISSUE TITLE
Button to empty log in log file viewer

### ISSUE THREAD

**Issue by Williwillswisse** [FSGModding/FSG_Mod_Assistant#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Great work! Thanks for the tool.

I am often involved in modding and would find it very helpful if the log file viewer had a button to empty the actual log.txt.
Maybe in this area:

![image](https://github.com/FSGModding/FSG_Mod_Assistant/assets/47098121/0d2c6feb-4d6c-4728-bc3e-8975b6b2088c)

**Comment by jtsage** [comment]
So, I did add a clear button - note that this is only going to work when the game isn't running.  The game does indeed lock the log file - at least the giants e-shop version does. You *might* be able to get around this with permission escalation, but that's not something I have a way to support. (similar problem exists for symlink support)  But, the button is now there - it just writes an empty string to the file, so it won't delete an existing file, just clear it.

**Comment by jtsage** [comment]
Implemented in 3.1, releasing this weekend
