### ISSUE TITLE
[FEATURE] A clearer information window

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Would it be possible to add coloring to the displayed information in the mod details window?
![image](https://github.com/FSGModding/FSG_Mod_Assistant/assets/2678653/041174a2-a00c-47bc-a391-12cd5eb4ab52)
Something like this:
![image](https://github.com/FSGModding/FSG_Mod_Assistant/assets/2678653/59cca61c-454e-41a6-b666-e5868aa0a59c)

**Comment by jtsage** [comment]
yep, done.

![2023-08-08 17_15_11-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/bd7841e5-af0f-4929-a81a-668aa6f0ca15)

**Comment by jtsage** [comment]
Extra / Oversized / Space & PNG display red when there is something, key bindings in the info (blue) color
