### ISSUE TITLE
[FEATURE] Save Game management

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Maybe a module to handle local savegames?  Delete, restore backup, etc?

**Comment by FSGModding** [comment]
What about "Cheat" options? Finances, equipment, etc

**Comment by jtsage** [comment]
I'm not sure cheat options are a road I really want to travel.  Some things are pretty straight forward - money & land ownership.  But stuff like vehicles you have to put them somewhere - and that requires knowledge of the map that MA just doesn't have right now.  There is also the caveat that *when* something goes wrong with a save (and it will), MA will get blamed.

This is compounded by the fact that MA is only useful on PC, and easy dev does so much of the cheat-y stuff so well already.

**Comment by jtsage** [comment]
Implemented in 3.1, releasing this weekend.
