### ISSUE TITLE
[BUG]Caught rejection: TypeError: thisModRecord.modDesc.depend is not iterable (cannot read property undefined)

### ISSUE THREAD

**Issue by PavementPilot** [FSGModding/FSG_Mod_Assistant#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating I ran into this
[crash.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/12326719/crash.log)

### Environment

```markdown
- Mod Assistant Version: 3.0.0
- OS:Windows 11
- Game Version Giants E-Shop
```

**Comment by jtsage** [comment]
Sorry - I missed this somehow.  You can manually clear your cache and this should fix it, or give me a day or two to get the next version out.

To manually clear your cache, hit [WIN_KEY] + [R] and type `%appdata%`, navigate to `fsg-mod-assistant` and delete the `mod_cache.json` file
