### ISSUE TITLE
Change game settings per game save [FEATURE]

### ISSUE THREAD

**Issue by ArgsyGaming** [FSGModding/FSG_Mod_Assistant#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

would it be possible to use MA to manage game settings per game save - I'm thinking things like units - km/mile, $/£/€, acres/ha etc.

**Comment by jtsage** [comment]
I did all 4 unit measurements - money, temperature, distance and area.  Most of the other settings don't really seem like collection-specific things.

![2023-08-19 09_45_53-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/d3a4fd7f-2fb5-4697-bb41-6bae54f22960)


I had a brief thought about key binds, but it would be a mess, and prone to error - getting your preferred key bind file in is easy - but how to track when you make changes, and what collection those changes go with would just be a nightmare.
