### ISSUE TITLE
[BUG] Symlinks support? ma doesnt pick up all mods

### ISSUE THREAD

**Issue by judg393** [FSGModding/FSG_Mod_Assistant#17]
**Describe the bug**
Isn't loading all mods 

I have 236 mods in my Silverrun folder when i add the folder it reads and test 236 but only then displays 8 

Could this be something to do with the fact that the mods are symlinks though it is picking up some of those mods? 

Adding my main mod folder (where i keep one version of all the zip files and sym link from to other folders works as expected so unsure if this is a bug or just the programme doesnt work with symlinks? 

**To Reproduce**
1. use link shell extension to create a symlink in a map mod folder 
2. Click on add folder select the symlink folder (with symlinked mods inside)
3. MA Processes mods  
4. only 8 mods are then loaded in to MA

**Expected behavior**
all mods should load

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
[assist.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/10073293/assist.log)
![Capture](https://user-images.githubusercontent.com/55981682/203487818-55e6f832-fc6b-4bdb-b975-e60d72c759b3.PNG)
![Capture1](https://user-images.githubusercontent.com/55981682/203487825-7ad2b7d1-9949-499b-b18b-5e91f0567ad1.PNG)

**Comment by jtsage** [comment]
From the log:

`2022-11-23 06:32:54 |  DANGER | folder-reader >> Couldn't process D:\FS22\SilverRun: Error: ENOENT: no such file or directory, lstat 'D:\FS22\All Mods\FS22_AirFlex_Series_4K.zip`

My guess is that `D:\FS22\All Mods\FS22_AirFlex_Series_4K.zip` does not exist anymore.

And I did a really poor job of making sure a symlink is valid before looking at the file is (supposedly) points to.

Added some error trapping and some good informational messages for just this issue. 

__FWIW__
-  if you `copy` a symlink, it will copy the __REAL__ file
- if you `move` a symlink, it will move the __LINK__ descriptor (leaving the original, linked-to file intact)
- if you `delete` a symlink, it will delete the __LINK__ descriptor
