### ISSUE TITLE
[BUG]Application stalls while loading mod folders

### ISSUE THREAD

**Issue by aburco** [FSGModding/FSG_Mod_Assistant#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the update the application stalls every time while trying to load the mod folders.  
[assist.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/12424337/assist.log)
[crash.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/12424339/crash.log)
 I've attached the crash and assist folders from the app.

### Expected Behavior

I expected the application to load like the previous versions have. 

### Steps To Reproduce

I'm running the game via steam on a 64bit windows 10 environment

### Environment

```markdown
- Mod Assistant Version:3..1
- OS:64bit win10
- Virtualized:
```

**Comment by jtsage** [comment]
This likely got addressed, if not can you please re-open?  Thank you! (sorry for pretty much ghosting this report)
