### ISSUE TITLE
[FEATURE] Mini Version on minimize

### ISSUE THREAD

**Issue by tazman87** [FSGModding/FSG_Mod_Assistant#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

![FSGmodAsist_Mini](https://github.com/FSGModding/FSG_Mod_Assistant/assets/105547288/7ceaa751-9d2d-42d9-98d1-2b2e18f89063)

**Comment by jtsage** [comment]
![2023-12-02 16_10_24-mini_ui js - FSG_Mod_Assistant (Workspace) - Visual Studio Code](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/7d73b2ac-37fd-44ad-b30f-0250698a63da)

**Comment by jtsage** [comment]
In v3.3.0
