### ISSUE TITLE
[BUG] Program crash after running with the game running

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I had the game running (MP mode) and ran the program, this message appeared at the end of testing (593/600) and it was impossible to close it without using the task manager.

![image](https://github.com/FSGModding/FSG_Mod_Assistant/assets/2678653/16d2d9fd-31c6-4854-a4ff-4ed9229122a5)

LOG: [crash.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/12793946/crash.log)

### Environment

```markdown
- Mod Assistant Version: 3.1.0
- OS: Win 10
- Virtualized: No
```

**Comment by jtsage** [comment]
Woot.  You are the real MVP here - I was nearly positive there was some sort of error condition I was missing, this is clearly it! (it's a funky zip for reference, or just as likely, a file locking issue from the OS)

Either way, this is very helpful, I'll take a look.

Thanks!!

**Comment by jtsage** [comment]
Any update?  I'm going to close for now, please reopen if it persists.  Thanks
