### ISSUE TITLE
[FEATURE] Ignore select folders for Version Check

### ISSUE THREAD

**Issue by AZSparky** [FSGModding/FSG_Mod_Assistant#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

It would be pretty sick to be able to disable specific folders from the version check.

This way when there are modified files in a specific folder (such as the FSG Realism), it doesn't show up as a version mismatch.

This would require manually updating the files in this folder but keeps things pretty clean!

**Comment by jtsage** [comment]
![2023-10-18 13_01_25-Window](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/287d87bc-020e-46dd-b751-2643e53bd679)
