### ISSUE TITLE
[BUG] Window not showing - Offscreen due to change in monitor config

### ISSUE THREAD

**Issue by Stitchykins** [FSGModding/FSG_Mod_Assistant#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am experiencing an issue where the program opens and runs but I cannot see or use the program at all as the window is not visible. I can see the program is open and if I hover over the icon on the task bar I can see the preview of the window but not the application itself.

### Expected Behavior

I expect to see and use the program xD

### Steps To Reproduce

Open the program. It never shows but is running.

### Environment

```markdown
- Mod Assistant Version:3.1.0
- OS:Windows
- Virtualized:
```

### Anything else?

uninstalling and installing again does not solve the issue.

**Comment by jtsage** [comment]
Hrm.  that's an odd one.  Try nuking your preferences file (you'll need to re-add your collections, but the cache should still exist so it'll be quick(ish)) - Hit `Win+R`, type `%appdata%`, navigate to `fsg-mod-assistant` and delete or rename `config.json` - it might be that it saved the window position incorrectly somehow, that will reset it.

If you really, really want to do it the hard way - the applicable stuff is under "wins"->"main"->"x", "y", "w", and "h" - default for that one is w: 1000, h: 700, m: false, x: -1, y: -1

**Comment by Stitchykins** [comment]
Yup that got it. I had to send my main monitor off for repair recently so saving the window in the incorrect position makes sense.
Thanks for the quick response :)

**Comment by jtsage** [comment]
Sure thing - I'm actually gonna rename this bug a bit and leave it open - I think I can add some logic to handle if it's gonna place the window in a place that doesn't exist anymore.

**Comment by jtsage** [comment]
- https://www.electronjs.org/docs/latest/api/screen#screengetalldisplays
