### ISSUE TITLE
[FEATURE] Select 'UNUSED' or 'INACTIVE' from savegame comparison screen

### ISSUE THREAD

**Issue by judg393** [FSGModding/FSG_Mod_Assistant#19]
**Is your feature request related to a problem? Please describe.**

The ability to check your save game for inactive mods is awesome. 

**Describe the solution you'd like**

Even more awesome would be a delete all located inactive mods from the folder button maybe after you've run the comparison to a save game. 

**Describe alternatives you've considered**

I mean you can select and delete the mods by searching for them. But I  think a select all button would be useful. 

Or from the main window you could then filter by inactive. But I presume you need to run it against a save file to work out whether it's active or not hence the select all/ delete all button being within the compare save game to mod folder screen 

**Additional context**

I think there's space on the save game check window next to the icon  on the left.

**Comment by jtsage** [comment]
Hmm.  interesting idea.  Let me see if I can at least make a button in the savegame window that will select all the "unused" or "inactive" mods.  I don't really want to automate it completely, because particularly the "unused" tag can be wrong in some situations (mostly mods that add only stuff like buyable bales or pallets - if you don't have any bought *right now*, it'll show unused, even if you intend to use it.)

But a button in the savegame screen that will select them in the other window seems plausible, lemme see what I can come up with.

**Comment by jtsage** [comment]
![2022-12-05 19_51_53-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/205779057-b6d0be9f-fb2c-4bb1-890d-b9b41579214d.png)

**Comment by jtsage** [comment]
Closing this as finished, feel free to re-open if needed :)

**Comment by judg393** [comment]
Awesome I love how supportive you are of changes. Thanks I'll check it out when I next play :) 

Also thank you getting symlinks to copy as symlinks with MA this was my biggest issue with alternatives now the feature set of MA and this alone has me using MA exclusively

**Comment by judg393** [comment]
Uh did I reopen this to say thanks? If I did sorry

**Comment by jtsage** [comment]
Heh, nope, all good.  Regarding links, I am still playing with the idea of allowing links to be created from in the app.  Just not there quite yet.

**Comment by jtsage** [comment]
Alas, additional symLink support will not be coming.  Bummer, it would have been nice.  See also #24

**Comment by judg393** [comment]
No problem completely understand why you wouldn't want admin access in your programme just checking it will still be able to duplicate symlinks as symlinks using the copy button?

**Comment by jtsage** [comment]
I'll double check what the behavior is right now, I'm really not sure.  It *should* be whatever the default windows behavior is

**Comment by judg393** [comment]
I believe windows defaults to copying a sym link as a zip file :(

**Comment by judg393** [comment]
Hi @jtsage this feature (selecting of inactive mods) and then deleting is working a treat 

2 further requests on the same line if they don't merit inclusion then that's cool 

1) could the window that pops up to warn you that deletion is irreversible allow you to unselect files too? Maybe it does but I wasn't able to test it 

2) anyway the select all inactive mod button you added at my request could disregard CSV files? It keeps deleting my mod file list cos I keep it in the same folder😂 I would presume it only needs to be able to delete folders and zips? Not sure if that's possible to code 


Cheers All

**Comment by jtsage** [comment]
Reopening to look at both of these.  of the two, excluding CSV files is gonna be pretty simple.  Lemme think about the other one - my constant fear is overcomplicating (more than I already have) the interface.

**Comment by judg393** [comment]
Haha 

If you can make 2 Happen forget 1 it's just me being lazy not wanting to have to unselect to be honest it only popped into my head cos I kept deleteing my csv 😂
