### ISSUE TITLE
[FEATURE] Is it possible to add data from <combination…/> lines of .xml object files?

### ISSUE THREAD

**Issue by vitalii2011** [FSGModding/FSG_Mod_Assistant#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by jtsage** [comment]
Um, yeah, actually.  It'll still be potentially limited - but with the addition of the base game stuff, that covers all of those, and most mods will either reference base game or their own combinations, so, yeah, should work.

Lemme play with this today - great idea!

**Comment by jtsage** [comment]
![2024-01-14 11_20_10-basegame html](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/39427afa-5917-474d-a136-27465b429eea)

Getting somewhere.  The image / brand image / title are clickable to open the details.  The little orange guy is the compare button.  I was gonna do a "compare all" button at the title.  Opening in a new window is actually pretty difficult because of how I have to do window management, but I'll look into it.

**Comment by jtsage** [comment]
Just trying to think this through, and I have a few other things to do today.  But

Base Game browser 
- Show combos in detail page
- Link combo to combo detail page
- Allow individual compare and "compare all"

Mod Look Details
- show combos inline in "detail" page
- link basegame combos to "deep link" to base game browser
- no link for combos internal to same mod (unless I can just make it scroll to it)
- compare individual and compare all

**Comment by jtsage** [comment]
Sigh.  Stupid amount of work pending.

It occurs to me that this will only list the *specified* combos - but lots of other equipment will work.  I'd just need to parse the attacherJoints on each item.  So, yeah, gonna do that too.  So much for a release today :)

Fwiw @vitalii2011 - I have not yet added the bit to force refresh of the detail cache (orange button in the "Mod Cache" bit in user preferences) - but every time I add something to the parser that needs hit or these features are going to rest pretty wonky.

**Comment by vitalii2011** [comment]
`this will only list the specified combos - but lots of other equipment will work` 
For some reason, this is not done even by the game mechanics. Maybe it's very complicated and/or the Giants skipped/didn't work on it because of the difficulty.

**Comment by jtsage** [comment]
My guess is they wanted the brand limitation, even though there isn't really one.  I'm gonna run down this road, of course things are gonna get real interesting when I hit `trailer`, `trailerLow` and `trailerHigh` - because there are a ton of them.  I think I will also add *which* joints are available on a vehicle/implement in the info box.

**Comment by vitalii2011** [comment]
`My guess is they wanted the brand limitation, even though there isn't really one. I'm gonna run down this road, of course things are gonna get real interesting when I hit trailer, trailerLow and trailerHigh - because there are a ton of them. I think I will also add which joints are available on a vehicle/implement in the info box.` 
This is a huge job. Is it necessary? But, if you are interested, good luck and discoveries!
In any case — your application is already the best. (I hope I watched everything for this series of games).

**Comment by jtsage** [comment]
So, this wasn't the real time consuming rabbit hole - the real time consumer is I started needing a few icons, so I pulled them in, but they were ugly, so I generated SVG versions for all of the game icons I use - including fill types.  Hopefully I'll make some real progress on changing over the use of static files with the new SVG this weekend and get a release out.

**Comment by vitalii2011** [comment]
- Is it possible in this window to filter by engine power (maybe by speed) or display these values?
![0011](https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/e6f2a41e-1885-4bbb-ac1b-95c5c816057f)
- The price, of course, is interesting, but in this game money is earned so easily :) that it is the last thing that interests you.

**Comment by jtsage** [comment]
Oh, I don't hate that at all - yeah, should be possible.  I based my display off of the in-game store one, but adding it there should be no problem.  Filtering might take a bit more, but I'll look into it

**Comment by vitalii2011** [comment]
For combine harvesters, the determining factor is the capacity of the bunker (instead of ~speed?); Based on this, a trailer is selected, and a tractor is selected for the trailer. 
Of course, this is just about my playing style. Many people prefer to play realism and the price of transport and equipment is important to them.

**Comment by jtsage** [comment]
No, I see what you mean.  I am working my way through my incredibly convoluted code on a couple sections today - breaking things into reusable libraries - there is no reason when I get to the vehicle/implement items I can't add some additional logic to include the bits that matter. One of my major complaints on a few of the other options out there is they throw a massive amount of largely unimportant data in your face, I don't want to follow suit, I want to be better :)

**Comment by jtsage** [comment]
![2024-01-20 13_22_46-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/64849f85-a837-495d-8c7b-f82b270e9c97)

something like this maybe? (still a ways to go, but getting prettier by the minute)

**Comment by vitalii2011** [comment]
Yes. Certainly.

**Comment by vitalii2011** [comment]
Maybe to save space, if in "<motorConfigurations> ... </motorConfigurations>" there is only one entry "<motorConfiguration ... </motorConfiguration>" show only one/maximum(?) engine power?
![Image 002](https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/706fa6ff-bb2e-44be-9965-749472e45069)

**Comment by jtsage** [comment]
Sigh.  Yes indeed.  The brutal thing is I had this working earlier, and clearly messed something up during all the code refactoring and it reverted.  Good catch.
