### ISSUE TITLE
In 1.3.3 "Load Save Folder" does not work[BUG]

### ISSUE THREAD

**Issue by vitalii2011** [FSGModding/FSG_Mod_Assistant#21]
**Describe the bug**
In the title

**Expected behavior**
When I select a save folder and try to open it, nothing happens.

**Desktop (please complete the following information):**
. Windows 10

**Comment by jtsage** [comment]
Ew.  This one is totally on me, give me about 2 hours or so.

**Comment by vitalii2011** [comment]
Everything is great in 1.3.4 . Thanks for the correction.
"Select in Main Window" is a great feature.
