### ISSUE TITLE
[BUG] Browse Base Game Items

### ISSUE THREAD

**Issue by mdrollins1983** [FSGModding/FSG_Mod_Assistant#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Reporting a bug when attempting to open file location of game items when exploring "Browse Base Game Items" \x64\ needs removed from filepath.
![image](https://github.com/FSGModding/FSG_Mod_Assistant/assets/94983108/768bb2db-581a-42a2-8af8-152fbb2a1b60)

### Expected Behavior

Then selecting "Open Folder in Explorer", it should open file explorer to the data folder where the game's asset is located.

### Steps To Reproduce

1. Select "Browse Base Game Items" button at taskbar at top of the program window. 
2. Select a base game asset category.
3. Select the base game asset.
4. Select "Open Folder in Explorer".

### Environment

```markdown
- Mod Assistant Version: 3.4.1
- OS: Windows 11 Pro
- Virtualized:
```

**Comment by mdrollins1983** [comment]
![image](https://github.com/FSGModding/FSG_Mod_Assistant/assets/94983108/d3397573-1f2b-44a8-a5a3-247b32cdd9b5)

**Comment by jtsage** [comment]
oh.  huh.  I can check for that.  For reference though, 

![2024-01-24 20_23_22-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/47312244-9da6-4c8a-9688-3be560b8c5dc)

**Comment by mdrollins1983** [comment]
I'm positive it's a simple fix of ensuring that \x64\ is removed when opening game assets. Most assets are located in Farming Simulator 2022\data and not Farming Simulator 2022\x64. There is no data folder located within \x64 folder.

**Comment by mdrollins1983** [comment]
C:\Program Files (x86)\Farming Simulator 2022\FarmingSimulator2022.exe is if the user want to launch GIANTS updater first. I prefer to launch the actual game directly in the \x64 folder instead of GIANTS updater checking for game updates first.

**Comment by jtsage** [comment]
Huh.  I didn't know that.  Yeah, I can add a logic trap to remove that part of the path if it exists. Expect it in the next update whenever that happens.
