### ISSUE TITLE
[BUG] Disabling older FS does not disable XML file checking

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After setting up collections for FS22 and, for example, FS19 (assigning the gameSetttings.xml file) and disabling multi-game support (but the collection for FS19 was still enabled and the data was not deleted), the program tries to continue checking collections for FS19. I noticed this problem after deleting the files from "My Games/FarmingSimulator2019", and the program's log showed an entry about the inability to load the gameSettings.xml file from the "FarmingSimulator2019" folder, although I checked that the "Multiple games" option was disabled, but I enabled it and the data for FS19 was completed and this collection was enabled.

### Environment

```markdown
- Mod Assistant Version: 3.4.1
- OS: Win10 22H2
- Virtualized: No
```

**Comment by jtsage** [comment]
Oh, nice catch.  Corrected for the next release

**Comment by jtsage** [comment]
Fwiw, if you find the error messages annoying, you can turn multi-mode back on, toggle that game version off, and then turn off multi-mode again.  I just missed the check of the "umbrella" flag :)

**Comment by jtsage** [comment]
If you are feeling particularly adventurous, I just pushed a 3.5.0-RC1 pre-release that includes this fix (and in all honesty probably adds a bunch of bugs, we shall see :) )
