### ISSUE TITLE
[BUG] Button overlap

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the LOG preview window the minimize and delete button overlap (see ss), in addition there will be an option to translate texts (and descriptions) in this window? 
![image](https://github.com/FSGModding/FSG_Mod_Assistant/assets/2678653/8cdb94f4-42c8-4f49-8e45-113b20b5c0c4)

PS: The bug is also in version 3.4.1

### Environment

```markdown
- Mod Assistant Version: 3.4.91
- OS: Win10 22H2
- Virtualized: No
```

**Comment by jtsage** [comment]
bah, gross - I saw it the other day too and forgot to write it down.  Thanks, I'll correct.
