### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by n0rq** [FSGModding/FSG_Mod_Assistant#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Love the MOD Assistant!!! TY for your hard work.

If the mod is newer(higher version), don't suggest downgrading to mod hub version as an option.

My request is to also check on GitHub if there is a new version if a link to GitHub is added. 

For example, FS22_Courseplay is at the moment 7.4.0.2 on Git Hub. on Modhub it is 7.4.0.0

**Comment by jtsage** [comment]
Thanks for the kind words.  So, yeah, your request.  Here's the problem - and I understand the text "update" isn't awesome, but:

__GitHub__ : the release mechanism is not awesome to query. getting the "latest" version as a string is problematic - it involves following a bunch of redirects, it's error prone, and it takes a long time (from a processing standpoint).

__ModHub__ : figuring out if the modhub version is older or newer is *hard* - had giants choosen to use semantic versioning, this would already exist - but it is totally valid for a modhub mod to have a version like 1.2 or 1.0.0.0 or 1.0.1 - they have gotten better about forcing the 4-part version string, but then you have odd mods that include text in there too. It is just incredibly error prone to parse, what I do now is check and see if the two versions strings aren't the same, and then throw the "update" flag.

I'll continue to explore this, but I am not hopeful I can arrive at a stable solution.  Thanks again for the input
