### ISSUE TITLE
[BUG] new user here, but the download just installs without asking anything and won't startup

### ISSUE THREAD

**Issue by Orsa1305** [FSGModding/FSG_Mod_Assistant#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the installer download just shows a window saying installing, the app is then installed, according to windows 11, but starting it doesn't do anything.
I even tried the portable version, never starts anything.

### Expected Behavior

show me the programm

### Environment

```markdown
- Mod Assistant Version:351
- OS:Windows 11
- Virtualized: No
```

**Comment by jtsage** [comment]
Huh.  yep, sure does.  I missed a character on a tiny bit of code that only ever runs the very first time MA starts.

All fixed, you can grab it here (it can just get installed over what is already there) : https://github.com/FSGModding/FSG_Mod_Assistant/releases/tag/v3.5.2

**Comment by Orsa1305** [comment]
wow, quick response and thanks a lot.

**Comment by Orsa1305** [comment]
wow, quick response and thanks a lot.
