### ISSUE TITLE
[BUG] Child Process failing

### ISSUE THREAD

**Issue by SergeySLV** [FSGModding/FSG_Mod_Assistant#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello! Thank you for such work, but I have a problem. When you select a folder that contains mods, it says that an empty collection or mods are hidden by filters. There are definitely mods there, the game sees them, what kind of filters could there be? I tried other versions of the program. I also tried a folder with three mods - the same result. Although when reading, he sees the number of mods in the folder.
![Screenshot_111](https://github.com/FSGModding/FSG_Mod_Assistant/assets/160548111/24a97109-aba8-4fbf-9b80-aa9ccc95a167)

### Environment

```markdown
- Mod Assistant Version:3.5.1
- OS:Windows 10
- Virtualized:no
```

**Comment by jtsage** [comment]
It's more a visual bug - you are in "Edit Folders" mode - try clicking that button so the collection order buttons go away.

**Comment by SergeySLV** [comment]
Same thing, folder size 0...

**Comment by jtsage** [comment]
huh.  that's real odd.  and if I understand correctly, when you hit "reload folders" it does count the mods that are actually there, they just don't seem to be showing up in the list. That 0 mods / 0kb is *before* any filters too, so this leads me to believe that there is a problem with the parser itself.  Can you copy and paste the full path to that mod folder here?  I do not speak ?russian?, but I do want to recreate the path locally here to make sure it's not having a problem with the non-latin characters (it should be fine, but one never knows with windows)

**Comment by SergeySLV** [comment]
C:\Users\User\Documents\My Games\FarmingSimulator2022\mods

**Comment by SergeySLV** [comment]
I would like to add that program versions 3.5.2 and newer do not run for me. In version 3.2.0 everything is the same as in version 3.5.1

**Comment by jtsage** [comment]
Huh.  odd.  can you send me your config file - if you press `WinKey` + `R`, then type `%appdata%` and browse to `fsg-mod-assistant`, there will be a `config.json` in the folder.  I wouldn't mind a copy of `assist.log` and `crash.log` if either are there.  Thanks.

**Comment by SergeySLV** [comment]
[crash.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/14337497/crash.log)
[assist.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/14337498/assist.log)
[config.json](https://github.com/FSGModding/FSG_Mod_Assistant/files/14337499/config.json)

**Comment by jtsage** [comment]
excellent, thank you.  yeah, let me dig into this tonight a bit - there is very clearly something odd going on here - at a guess, it's trying to use an invalid temporary folder, but I'm not really sure yet.

**Comment by SergeySLV** [comment]
Maybe this will help somehow, the program sees the game (viewing equipment) and saves with a list of mods.

**Comment by SergeySLV** [comment]
Thank you for such a program and for your help. I'll be looking forward to the decision.

**Comment by jtsage** [comment]
this is kinda notes for myself, but, in your crash.log - 

![2024-02-19 18_06_47-crash log - Notepad](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/113fd618-d238-4dcd-bbd5-7d3923e19f79)

that's one of the scanner threads failing to be able to report back.

but this is the icon parser failing before that

![2024-02-19 18_07_33-crash log - Notepad](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/f839ef3d-568f-485f-9109-5c0fd4354880)

Oh, another question for you (and I should really add this to the original bug report) - is this the portable version? (I don't do nearly as much testing with that)

**Comment by SergeySLV** [comment]
I tried both portable and exe

**Comment by SergeySLV** [comment]
Hello! Let me know, did you solve the problem?

**Comment by jtsage** [comment]
I'm really not sure if this is solved or not - if you are still around and messing with it, give one of the pre-releases a shot (on the release page).  There were a bunch of changes to error handling, hopefully this got scooped up in them, as I have been totally unable to reproduce the problem.
