### ISSUE TITLE
Folder Edit display

### ISSUE THREAD

**Issue by DanL58** [FSGModding/FSG_Mod_Assistant#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When changing the folder display order it jumps to the top of the list after every move and you have to scroll back down again to move the folder again. Could it be made to stay in the position you are currently working?

**Comment by jtsage** [comment]
probably, yes.  adding to the list.

**Comment by jtsage** [comment]
added in current dev copy, will be included in the next full release.
