### ISSUE TITLE
[BUG]FSG Mod Assistant Steam Game Arguments

### ISSUE THREAD

**Issue by regs1980** [FSGModding/FSG_Mod_Assistant#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Start the game via the FSG Mod Assistant, Steam gives me the message "Launch Game with custom arguments", although I have not entered any game arguments in the FSG Mod Assistant.
![2024-02-28 18_46_15-FSG Mod Assistent](https://github.com/FSGModding/FSG_Mod_Assistant/assets/13314443/20b97666-0699-4683-8de3-52a69808a1ce)
![2024-02-28 18_47_42-Steam](https://github.com/FSGModding/FSG_Mod_Assistant/assets/13314443/4bc12b0f-a6b1-479b-99db-6b5d9a5c8925)

### Expected Behavior

Start the game via the FSG Mod Wizard without the Steam message. 

```markdown
- Mod Assistant Version: 3.5.2
- OS: Win 11

**Comment by jtsage** [comment]
Do you have any launch parameters set in steam?  This is a shortcoming of steam, they must match between the two programs, although the options set in MA are the ones that will "win"

**Comment by regs1980** [comment]
There are no launch parameters inserted in steam.
If I start the game via Steam, this message does not appear.

**Comment by jtsage** [comment]
huh.  I'll do some experimenting.  It might be an issue with an empty string and steam is confused.

**Comment by n0rq** [comment]
> There are no launch parameters inserted in steam. If I start the game via Steam, this message does not appear.

@regs1980 Try to "Clean Cache" and see if it solves the issue if not then "Clear Detail Cache (SAFE!)"

I had a similar issue about a week ago when FSG stopped starting FS22. I was about to open a ticket and decided on a whim to run one after the other. Afterward, the game started right up from inside FSG M A. Post your findings.

**Comment by regs1980** [comment]
> Try to "Clean Cache" and see if it solves the issue if not then "Clear Detail Cache (SAFE!)"

That was the first thing I tried.
I can do this as often as I want, the message still appears.

**Comment by jtsage** [comment]
I cannot for the life of me reproduce this - I've tried empty lists in both steam and MA, and all sorts of odd empty spaces as well.  Any chance you can send me your config file - it'll be at `Win+R`, type `%appData%`  go to `fsg-mod-assistant` folder, and send the `config.json` file.

Thanks

**Comment by regs1980** [comment]
I have completely uninstalled the Mod Assistant and deleted the remaining files.
Now use the portable version and it works.
It will also work with the installed version, but I have not tested it.
Must have crept in at some point during a Mod Assistant or Steam update.

**Comment by Theovorn** [comment]
Greetings.
I have the same situation, where Steam warns me about trying to launch with "" parameters.
It seems to me that the field "game_args_25" in the config.json is not seen as empty, even if its set to "".
This seems to happen only for FS25 because I also have FS22 set the same way and there's no issues.
