### ISSUE TITLE
[BUG] Hints remain after selecting the window

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you hover over the options at the top right of the window (log, settings, search, etc.), hints appear and stay if you select an option.

### Expected Behavior

The hints should disappear xD

### Steps To Reproduce

1. Hover the cursor over any of the top options (such as viewing the game LOG file).
2. A description/hint appears, click this option to open a new window.
3. Turn off the window and look up, the description/hint is still visible.
4. Hover the cursor over other options, new descriptions/hints appear and the one last selected does not disappear.

### Environment

```markdown
- Mod Assistant Version: 3.5.2 and 3.9.71 and 3.9.91
- OS: Win10 and Win11
- Virtualized: No
```

**Comment by KITT3000** [comment]
After updating to 4.0.0 error now appears only for the option "View Documentation"

**Comment by jtsage** [comment]
doh.  of course it does.  because that uses the URL handler, not the window library.  ok, I shall fix.

**Comment by KITT3000** [comment]
Then there is this case:
1. Select an option such as viewing LOG.
2. Close the window.
3. Collapse the program window to the windows taskbar.
4. Restore the visibility of the window, the prompt suddenly appears and stays.
