### ISSUE TITLE
Sort folders alphabetically

### ISSUE THREAD

**Issue by Albschwob** [FSGModding/FSG_Mod_Assistant#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

In older versions you could sort them alphabetically under "Edit folders". Is this no longer possible or have I overlooked something?

**Comment by jtsage** [comment]
no, you're not missing something - I got lazy, and didn't think anybody was using it, so when I redesigned the "Edit Folders" interface, I got rid of it.  However, you are not the first person to ask, so I'll add it back in sometime soon.

**Comment by Albschwob** [comment]
Great. The program is excellent and helps a lot with organizing the farming simulator. If the sorting is running again it is unbeatable. 5 stars and thank you for the great work.
