### ISSUE TITLE
[UPDATE] Can Mod Assistant create symLinks?

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#24]
This is a pinned message to refer back to, but the short answer is: **no**

The longer answer is:

To create a symLink in windows 10+, one of the following needs to be true:
1.) You need to be a local admin with development mode turned on
2.) You need to edit the group policies to give yourself the symlink privilege.
3.) The entire program needs to run with elevated access (as Administrator)

As we don't like any of these ideas, the decision has been made to not include this functionality at this time.  Should these requirements change in the future, this will be reconsidered.

**Comment by FlyingMasterChef** [comment]
I was coming here to actually ask for exactly this feature. I use an app with Flight Sim that uses the symlink feature so add-ons can be kept on different drives. It really is a Godsend... I would like to have this feature re-thought if you would for Mod Assistant (which I have come to LOVE, btw!!!!) My Documents folder (thus my mods folder) is located on my OneDrive.  Using Symlinks would allow a HUGE space savings when copying mods from my ALL MODS folder and the FAVORITES folder to other folders. For example, my ALL MODS folder is 17 gigs. My FAV folder is 120 megs. If I copy my fav folder to all my map folders that adds another 2.8 gigs. If I then put in other mods mods in various maps it quadrupled the size of the mods folder. This ends up being real pain on some of my computers. Symlinks would remove this issue completely.  And while I get that you don't like the restrictions for using it, shouldn't it ultimately be up to the end user?  I mean, can't you simply add it as an option to use hard links or symlinks for the COPY TO function?

Anyway, I really do love this app and I thank you very much for it.  And thank you for at least reading my thoughts and possibly giving it another thought.

Greg Swagler 
Flying Master Chef
