### ISSUE TITLE
[FEATURE] sort mods by name 

### ISSUE THREAD

**Issue by jareckus** [FSGModding/FSG_Mod_Assistant#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Hi, is there any chance that there will be feature to sort mods by its name or author or time installed? now mods are sorted only by filename

**Comment by jtsage** [comment]
This is added to the current testing version.  You can sort by shortname (zip name), title, author, version, and file date.
