### ISSUE TITLE
[BUG] Caught rejection: TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by sashaman** [FSGModding/FSG_Mod_Assistant#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Program starts, and shortly after throws error and quits 

```
rejection Timestamp : 2024-05-11T08:18:01.263Z

Caught rejection: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

Origin: [object Promise]

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:406:5)
    at validateString (node:internal/validators:162:11)
    at Object.basename (node:path:756:5)
    at Object.setActivity (C:\Users\Aekzl\AppData\Local\Programs\fsg-mod-assistant\resources\app.asar\lib\modAssist_func_lib.js:692:141)
    at Timeout._onTimeout (C:\Users\Aekzl\AppData\Local\Programs\fsg-mod-assistant\resources\app.asar\lib\modAssist_func_lib.js:677:32)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)rejection Timestamp : 2024-05-11T08:19:24.521Z
```

### Expected Behavior

no error expected

### Steps To Reproduce

idk how to reproduce, i could not test on another machine. 
i know it is the same issue with v4 and v4.01

### Environment

```markdown
- Mod Assistant Version: 4.0.0 and 4.0.1
- OS: Wi11
- Virtualized: No
```

### Anything else?

[crash.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/15282177/crash.log)

**Comment by sashaman** [comment]
the same happens with 3.5.2 and 3.9.91 as well. 
idk what path it refers to, but nothig fancy in any of the possibilities tbh, not file system, not sys PATH, not fs or any of its mod paths....

**Comment by jtsage** [comment]
huh.  that's odd.  I'll try and track down why this is happening.  New install, or upgrade?

as for what path it means - something I am searching for or supplying, the path in question is actually the node:path package - specifically the "basename" function.  I had thought I had undefined traps on all of them, but clearly not.  Thanks for the report.

**Comment by sashaman** [comment]
i never ran into any issues with it before, got a new system setup so its a fresh install. 
thx for the path explanation, that gives hints. i have to admit i have anaconda installed, and probably various different packages/versions/environments, what is unclear to me is how it would mix up anything in there, or why it would not pick up set environment variables within. 
anyways, if i can supply anything that helps you  let me know. 
have a great sunday, cheers!

**Comment by jtsage** [comment]
so, this is in the discord status update stuff.  I don't know how the variable it's looking at can become undefined, but I added a trap for it.  Fix will be in 4.0.2 (or 4.1.0 depending on how much I do) later today

**Comment by jtsage** [comment]
closing for now, please reopen if the problem persists in the next released version

**Comment by sashaman** [comment]
works, no force close or anything, thanks a lot. 

i just wanted to give you additional feedback on the issue when i saw you talk about discord status in your explanation. 
i use vencord.dev , a discord modification, might be impacting on whatever you tried to read... 

cheers mate!
