### ISSUE TITLE
Programm startet nicht richtig

### ISSUE THREAD

**Issue by klapero** [FSGModding/FSG_Mod_Assistant#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

nach der Installation von Vers. 4.04 bleibt es bei dem Anmeldefenster.

![Screenshot 2024-05-21 180227](https://github.com/FSGModding/FSG_Mod_Assistant/assets/120971048/9ab779be-189a-4f85-b2fb-ad6c3a59a301)

Dann mus ich in der Taskleiste mit der rechten Maustaste auf ModAssistant und dann  mit "FSModassistant" das Programm starten.
Bis zur Version 4.0.1 war auch alles bestens.

### Expected Behavior

das nach dem doppel klick auf Mod Assistent dieser auch gleich startet.

### Environment

```markdown
- Mod Assistant Version: 4.0.4
- OS: Win 11
- Virtualized: nein
- Steam
```

**Comment by jtsage** [comment]
Translating to english for archival state.

## Observed
After installing version 4.04, the login window remains.

Then I have to right-click on ModAssistant in the taskbar and then start the program with "FSModassistant".
Up to version 4.0.1 everything was fine.

## Expected
that after double-clicking on Mod Assistant it starts immediately.

**Comment by jtsage** [comment]
Yeah, I think I just found a fix for this - I was unable to reproduce on my usual computer, but my work computer is exhibiting the same thing.  Expect a fix shortly.

**Comment by jtsage** [comment]
This should be fixed in v4.0.5, just pushed live.

**Comment by klapero** [comment]
Hallo,

 

Danke für das Update. Funktioniert wieder .

Nur zur Info, alle Ordner mussten neu hinzugefügt werden.

 

 

Klaus-Peter Rohr

 

Von: J.T. Sage ***@***.***> 
Gesendet: Mittwoch, 22. Mai 2024 16:01
An: FSGModding/FSG_Mod_Assistant ***@***.***>
Cc: klapero ***@***.***>; Author ***@***.***>
Betreff: Re: [FSGModding/FSG_Mod_Assistant] Programm startet nicht richtig (Issue #245)

 

This should be fixed in v4.0.5, just pushed live.
