### ISSUE TITLE
[FEATURE] What do we add to make the "Open Source Website" Work?

### ISSUE THREAD

**Issue by CredenceHamby** [FSGModding/FSG_Mod_Assistant#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Kinda? Cant figure out how its suppose to work.

### Describe the solution you'd like

Better explanation of what this is and how we can make mods support it. Would be nice if mod authors can place a tag in the modDesc file that this button looks for so no matter where the mod is downloaded from it goes back to the official site.

### Anything else?

What do we add to make this work?

**Comment by jtsage** [comment]
How it works - https://fsgmodding.github.io/FSG_Mod_Assistant/mods.html 

Most of the way down the page, but basically, right click "Set Source Website" and fill in a url.

As to automating it - I've added entries for a small handful of popular script mods that either aren't on modhub or don't get updated as regularly there.  I'm not against a special key in the moddesc, but that would require modder support, and I just don't know if it's there.  (I'm also not sure if giants would require that key not be there for modhub)
