### ISSUE TITLE
[BUG] Small thing - no warning for failed file move operation.

### ISSUE THREAD

**Issue by onehandclapping** [FSGModding/FSG_Mod_Assistant#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to move a mod to another collection where that mod already exists there is no warning when the move fails.

### Expected Behavior

Just a dialog that says "Move Failed" or some such.

### Environment

```markdown
- Mod Assistant Version:4.05
- OS:W10
- Virtualized:No
```

**Comment by onehandclapping** [comment]
Sorry for the late update, my 3070 failed and had to be replaced (by a 4070 wahoo). 

Just a simple move from one "regular" to another. Selecting one or more mods and then clicking the "Move To" on the right.

**Comment by jtsage** [comment]
sorry for the delay, been busy.  I'm not sure I can replicate this

![2024-06-22 13_50_16-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/e33771ee-91ba-4b8d-a806-17b6aed24e57)

This is a file that already exists where I want to move it - if I don't hit the check mark, it does nothing.  If I do, it overwrites the file as expected.  But you are correct that there is no user-facing acknowledgement that (in this case) "1 file(s) will be skipped".  I could add something like that text to the button probably

**Comment by jtsage** [comment]
added a bit that says how many will be affected.

![2024-06-22 14_17_41-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/5fd3166c-46d8-460b-b94f-09643bff5fa5)

![2024-06-22 14_17_46-FSG Mod Assistant](https://github.com/FSGModding/FSG_Mod_Assistant/assets/605986/637022d1-906f-4db3-ba90-3b73054cc144)

**Comment by jtsage** [comment]
this is fixed in the testing version, there is visual feedback if anything failed.
