### ISSUE TITLE
[FEATURE] Add a keyboard shortcut to activate the "Show…" and "Find…" buttons with several mods selected

### ISSUE THREAD

**Issue by vitalii2011** [FSGModding/FSG_Mod_Assistant#25]
**Is your feature request related to a problem? Please describe.**
-1:
![0010](https://user-images.githubusercontent.com/41552153/209103498-98fed173-da96-469b-98fa-f3aee468776a.png)

-2: Maybe it makes sense to move the "language selection" to Settings? It is chosen, most often, no more than once) And the slightly overloaded interface of the main window will be cleared up a little.
![Image 001](https://user-images.githubusercontent.com/41552153/209106475-25b5ec53-23ee-4343-97b1-eae070ae61eb.png)

-3:
![Screenshot 2022-12-22 at 12-51-10 Файл en json - проект FSG Mod Assistant - перевод на Crowdin](https://user-images.githubusercontent.com/41552153/209107721-b40fe569-1aa0-408a-a381-4d53c62b0e88.png)

**Comment by jtsage** [comment]
Multi-message reply to follow.

#3 - adding another translation string - sure, done.  Pushed the new one to crowdin - it's the savegame screen, called `savegame_filter_only`

**Comment by jtsage** [comment]
2) yes....  how good is this at guessing the language (did you have to change it?) - As I recall, since this is a holdover of the Folder Checker, getting windows to actually change your language was a huge nightmare, so I had a hard time testing it.  I'm not against moving it to settings if it rarely actually needs to be touched.

**Comment by jtsage** [comment]
1.) yes, but - what should shift or alt clicking *do*?  Just turn the button on for the last selected?  Or should it alter the selection as well?  Or should it be a direct shortcut (alt+click opens the hub, and shift+click opens the file location)?  The file location is super simple, as it always exists, and it's a simple check to work or not for the modhub one.

**Comment by vitalii2011** [comment]
1. Alt, Shift, etc. - any of your choice as a modifier for "Just turn the button on for the last selected".
2. Yes, rarely (for screenshots :) ). Just advice, a view from the outside, a look "not a blurry eye." ))) And so - it doesn’t interfere at all, it doesn’t matter if it will be placed where it is now or in the Settings, or ....
3. Added translation

**Comment by jtsage** [comment]
1.) Probably ALT I think (of the three, ALT doesn't have a "normal" behavior for clicking, SHIFT+Click and CTRL+Click do in most programs) - this will be my next thing to work on.
2.) make sense.  Changing the language will now change it in all open windows now too, not just the main window
3.) got it, thank you.
4.) Indeed.  I had meant to add a meaningful description when we hit 1.0.0, and totally forgot.  Fixed.

**Comment by jtsage** [comment]
Above items are all included in release [v1.5.0](https://github.com/FSGModding/FSG_Mod_Assistant/releases/tag/v1.5.0)

**Comment by vitalii2011** [comment]
Thanks for v1.5.0.
Small remarks:
- Maybe that's how it was planned?
![0010](https://user-images.githubusercontent.com/41552153/210203603-adabe706-e50d-44dc-9f76-52b820b56dcb.jpg)
Now: It is not immediately clear what the description refers to:
![0010 - copy](https://user-images.githubusercontent.com/41552153/210203702-54b767b0-3b2c-4895-bc88-e1cbc289c5b4.jpg)

**Comment by vitalii2011** [comment]
Is it not possible to show the number of selected/filtered mods?
![0010](https://user-images.githubusercontent.com/41552153/210207078-61839721-dc93-4394-bfa0-651c5b70eff1.png)

**Comment by jtsage** [comment]
> Thanks for v1.5.0. Small remarks:
> 
> * Maybe that's how it was planned?
>   ![0010](https://user-images.githubusercontent.com/41552153/210203603-adabe706-e50d-44dc-9f76-52b820b56dcb.jpg)
>   Now: It is not immediately clear what the description refers to:
>   ![0010 - copy](https://user-images.githubusercontent.com/41552153/210203702-54b767b0-3b2c-4895-bc88-e1cbc289c5b4.jpg)

Yeah, saw the poor text too late - I'll work on that today.  Probably gonna require at least 1 new string and changing what they other 2 say.  I'll ping here when I mess with it so the crowdin update is more obvious.

Re: Quantity - sure, lemme see how to make it pretty :)

**Comment by jtsage** [comment]
![2023-01-02 13_33_11-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/210268301-8a96063d-6583-478f-ba6c-f215b0710636.png)
![2023-01-02 13_35_32-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/210268303-057334dc-c43c-4c7b-a2b5-94831ede9675.png)

**Comment by jtsage** [comment]
![2023-01-02 13_47_22-User Preferences](https://user-images.githubusercontent.com/605986/210269205-6e59729b-9986-4b2a-b126-0f6d1f5bc791.png)

In order, top to bottom:
- `user_pref_title_lang` [same]
- `user_pref_blurb_lang` [changed]
- `user_pref_blurb2_lang` [new]
- `user_pref_setting_lock_lang` [changed]

**Comment by vitalii2011** [comment]
I also wanted to suggest writing "on the buttons", but something distracted me.
Looks neat and just great.
![Screenshot 2023-01-02 at 21-55-05 FEATURE Add a keyboard shortcut to activate the Show… and Find… buttons with several mods selected · Issue #25 · FSGModding_FSG_Mod_Assistant](https://user-images.githubusercontent.com/41552153/210270256-a359fcaa-88d1-45ec-af27-0254d7abc26c.png)

**Comment by vitalii2011** [comment]
Done on Crowdin.

**Comment by jtsage** [comment]
Thank you.  Building 1.5.1 now :)

**Comment by vitalii2011** [comment]
"Script[0]" but they are there:
![Image 001](https://user-images.githubusercontent.com/41552153/210273604-2d678daa-5f88-4efd-9a63-caf95cfe188b.png)

**Comment by jtsage** [comment]
Gross.  Thanks, i'll get that fixed.

**Comment by vitalii2011** [comment]
When choosing a non-English (non-Latin) keyboard layout in the OS, the hotkeys for these 3 buttons do not work: 
![0010](https://user-images.githubusercontent.com/41552153/210333890-229b3872-399f-4ffb-98d9-695bb4c4195d.png)
"Add ALT+Click in main list to force modHub and "open in explorer" …", - works with any layout.

**Comment by jtsage** [comment]
Hmm.  What does this site show: https://www.toptal.com/developers/keycode if you SHIFT+CTRL+A on the non-latin keyboard layout?  Particularly this box:

![2023-01-03 11_12_11-Window](https://user-images.githubusercontent.com/605986/210396209-3c417d0c-79bc-4cd6-99ed-deb6c00d0584.png)

**Comment by vitalii2011** [comment]
```
![Screenshot 2023-01-03 at 19-23-09 JavaScript Key Code for ShiftLeft Toptal®](https://user-images.githubusercontent.com/41552153/210398160-50c14de8-cfaf-4b5b-809d-2d2dc86d4e0e.png)
```

**Comment by vitalii2011** [comment]
```
{
 "key": "Shift",
 "keyCode": 16,
 "which": 16,
 "code": "ShiftLeft",
 "location": 1,
 "altKey": false,
 "ctrlKey": true,
 "metaKey": false,
 "shiftKey": true,
 "repeat": false
}
```

**Comment by vitalii2011** [comment]
![Screenshot 2023-01-03 at 19-23-09 JavaScript Key Code for ShiftLeft Toptal®](https://user-images.githubusercontent.com/41552153/210398280-49167a87-1e94-4b9c-89ba-7acc7d555aa4.png)

**Comment by jtsage** [comment]
Hah.  That site isn't easy to use.  I did figure out how to add a russian layout to my keyboard, I believe I have a fix.  I was looking at the typed letter, not the key pressed.  Whoops.

**Comment by jtsage** [comment]
As a somewhat unrelated side note - I had not expected the "auto tag" bit of adding screenshots to crowdin - that is both amazing and so easy, sorry it's taken so long to post them.

**Comment by vitalii2011** [comment]
Yes, but this is a defect of the Crowdin administration if users "accidentally", "from someone" learn about the functionality of the site.

**Comment by jtsage** [comment]
I believe everything above is handled with 1.5.2, gonna close this one for now so I don't miss anything new :)  As always, thanks very much for your help.

**Comment by vitalii2011** [comment]
Yes, you have done significantly more than what was suggested at the beginning. ) 
Two small points:
- If I don't know what Crowdin is for, then the link to it at https://github.com/FSGModding/FSG_Mod_Assistant will not tell me anything, and in order to offer a translation into my own, not yet added language, I will open https://github.com /FSGModding/FSG_Mod_Assistant/tree/main/translations and add ~klingon.json (tlh.json). Maybe the item "Translations" in the description of the program at https://github.com/FSGModding/FSG_Mod_Assistant with a suggestion to use Crowdin will not be superfluous?
- About "Add ALT+Click in main list to force modHub and "open in explorer" ..." is not mentioned anywhere in the program itself, but I can't think of where it could and would be placed correctly.
