### ISSUE TITLE
[VERSION TESTING] v5.0.0-beta1

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#255]
# Version Testing

- Starting SHA: eee26714c66cde4820bfa8593d364088ac66b867

This is a list of all the functionality of FSG-MA

## Folder Management

- [x] Add Folder
- [x] Remove Folder
- [x] Missing Folder
- [x] Offline Folder
- [x] Drag New Folder
- [x] Reorder folders
- [x] Export CSV
- [x] Set active (button)
- [x] Set active (context)
- [x] Set inactive
- [x] Export as JSON (context)

## File Management

- [x] Drag file
- [x] Drag ZIP of files
- [x] Copy file - single destination
- [x] Move file - single destination
- [x] Copy file - multi destination
- [x] Move file - multi destination
- [x] Delete file
- [x] Show in explorer
- [x] Find on modhub
  - [x] No button if non-modhub
- [x] Find on source website
- [x] Copy favorites
- [x] Export ZIP
- [x] Open details

## File Management - context menu

- [x] Copy file - single destination
- [x] Move file - single destination
- [x] Copy file - multi destination
- [x] Move file - multi destination
- [x] Copy selected files - single destination
- [x] Move selected files - single destination
- [x] Copy selected files - multi destination
- [x] Move selected files - multi destination
- [x] Delete file
- [x] Delete selected files
- [x] Show in explorer
- [x] Find on modhub
  - [x] No button if non-modhub
- [x] Find on source website
  - [x] Set source website
  - [x] Un-Set source website
- [x] Open details

## Filters and Sorts

- [x] sort modes work
- [x] filter text works
- [x] filter tags work
- [x] select none
- [x] select all
- [x] select invert
- [x] show only selected
- [x] keyboard shortcuts for none/all/invert

## File Operation

- [x] no collection
- [x] conflict present
- [x] no conflict present
- [x] select all/none/invert

## Versions

- [x] Button state
- [x] Window opens and displays correct info
- [x] Resolve function works

## Detail page

- [x] Vehicle type
- [x] Map Type
- [x] Placeable type
- [x] Production type

## Basegame page

- [x] Vehicle type
- [x] Placeable type
- [x] Production type

## Savegame compare

- [x] from button
- [x] from dropped file
- [x] from listed file
- [x] select in main works
- [x] filters work

## Find window

- [x] filter works
- [x] select in main works

## Savegame tracker

- [x] opens
- [x] respects version
- [x] meaningful results

## Savegame manage

- [x] opens
- [x] respects version
- [x] import
- [x] export
- [x] duplicate
- [x] remove
- [x] compare

## Game log

- [x] opens
- [x] respects version
- [x] respects override
- [x] scrolls well
- [x] highlighting
- [x] filtering
- [x] find

## Debug log

- [x] opens
- [x] filters

## Collection details

- [x] opens
- [x] sets and reads properly

## Preferences

- [x] opens
- [x] sets and reads properly
- [x] clean cache
- [x] clear cache
- [x] clear detail
- [x] clear malware
- [x] font-size change
- [x] theme change
- [x] language change
- [x] open changelog
- [x] open wizard
- [x] game settings - toggle dev mode

## Extra UI buttons

- [x] crowdin
- [x] github
- [x] FSG modding
- [x] discord
- [x] help
- [x] launch button
  - [x] game poll respects version
- [x] mini window
  - [x] mini window status updates
  - [x] mini window active collection
- [x] minimize to tray
- [x] tray launch game
- [x] tray open mini
- [x] change version

## Import JSON

- [x] read json file
- [x] reject bad file
- [x] download

**Comment by vitalii2011** [comment]
Previously, the highlight background color of the selected mod was very good:
![0010](https://github.com/user-attachments/assets/9de98344-f986-418a-8a10-c486598ad5f1)
![0011](https://github.com/user-attachments/assets/e6b5cb1a-1913-4d76-8af5-c4e54cb99206)
If it is not difficult (or there are no reasons unknown to me for this change), please return it.

**Comment by vitalii2011** [comment]
In my opinion, "Find: …" is redundant (except as a hint). Because it can be searched just fine without switching:
![0015](https://github.com/user-attachments/assets/e7786a2c-240e-40ff-98fd-73eca7a458e0)
![0016](https://github.com/user-attachments/assets/0cd4105e-39cf-4775-8ed4-5865c9f5dd1c)
The full names of the categories do not fit. It is not clear why a search by "Version" might be useful.
![0017](https://github.com/user-attachments/assets/3da8265d-49aa-4d10-b02f-7f5b49ed9083)

**Comment by jtsage** [comment]
> Previously, the highlight background color of the selected mod was very good. It's hard to see on the big screen now:
> If it is not difficult (or there are no reasons unknown to me for this change), please return it. Or the ability to choose the color Classic/FS25(?), old/new.

Sure.  I wasn't sold on the darker one.  I find the brighter one a little too much so, maybe I'll see if I can turn down the brightness just slightly on the "old" one.

As to the search by term stuff - I agree that version is useless, I'll nuke it.  Most of the reason I added it was because I had to split those terms off for the sort feature to work.  My use case for changing it is this one - and it's really limited to much larger collections than I typically work with - but if you have "CASE" mods, and you want mods by the modder "Casearias", you'd get unwanted results by searching for part of the modders name.

**Comment by jtsage** [comment]
![2024-08-19 10_11_39-FSG Mod Assistant](https://github.com/user-attachments/assets/a769c743-5edd-43e8-9a7d-ee9d398abafa)
![2024-08-19 10_12_01-FSG Mod Assistant](https://github.com/user-attachments/assets/7d2149b5-3f77-490c-9eb9-2d7be72fe87c)

**Comment by vitalii2011** [comment]
![0010](https://github.com/user-attachments/assets/11a0664b-b172-4de1-ba39-689656c76895)
;)

**Comment by jtsage** [comment]
Yeah, I'm still on the fence about this one - it's somewhat intensive to actually do version comparisons, because it's not a forced standard format, so sorting it with a natural sort gets some things wrong - I don't know that it's really useful either, but it was requested.

**Comment by vitalii2011** [comment]
These buttons do not work:
![Image 001](https://github.com/user-attachments/assets/d6bb1d2f-1c46-4dfc-975a-af530e77c417)

**Comment by jtsage** [comment]
> These buttons do not work: ![Image 001](https://private-user-images.githubusercontent.com/41552153/359733967-d6bb1d2f-1c46-4dfc-975a-af530e77c417.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjk0MTAsIm5iZiI6MTcyNDI2OTExMCwicGF0aCI6Ii80MTU1MjE1My8zNTk3MzM5NjctZDZiYjFkMmYtMWM0Ni00ZGZjLTk3NWEtYWY1MzBlNzdjNDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE5MzgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NmU4OTViMzA4MWJjMzFhOTkzZTZiNDI0MWI4ODQ5ODBiYTNkZWRjYTZiYzQxMGRiYTlkYzczMjhkOWNjODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xjQTxUd8SH72KXJqxa3y-rAwof2nHEVU8cLMmA9L-mY)

Thanks.  I did the dumb - all of the translation stuff got moved to a new tag (they actually translate themselves, asynchronously, rather than me doing all of them at the end of page load - should be fewer, or at least shorter flashes where everything is empty)  Fixed though.

**Comment by vitalii2011** [comment]
These buttons do not work:
![Image 001](https://github.com/user-attachments/assets/3f03e8f0-a65b-4416-9918-3e657c34e749)

**Comment by jtsage** [comment]
> These buttons do not work: ![Image 001](https://private-user-images.githubusercontent.com/41552153/361180056-3f03e8f0-a65b-4416-9918-3e657c34e749.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NTE0MzIsIm5iZiI6MTcyNDU1MTEzMiwicGF0aCI6Ii80MTU1MjE1My8zNjExODAwNTYtM2YwM2U4ZjAtYTY1Yi00NDE2LTk5MTgtM2U2NTdjMzRlNzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDAxNTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMWEzZWNjYWZjNWJhZDhkNjFkYzYwZDBlN2ExYjkyN2NhN2I3ZDhiMWQ1NTM5Yjk5Y2E3NWU0ODA2MTYzNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l9GR0D9x66SU3UllXICwHQKE288N0uFQlYUyZWZ83yM)

That one was just silly.  Fixed in dev version, I'll likely build a new RC tomorrow - getting very close I think.

**Comment by vitalii2011** [comment]
This was reported at some point, but I don't remember what was decided.

https://github.com/user-attachments/assets/7cf15c50-0f42-485e-a46d-535791d93b68

**Comment by jtsage** [comment]
> For the following versions, if it's not too difficult: ![0010](https://private-user-images.githubusercontent.com/41552153/361731181-660b2443-52b4-4236-bb44-c11f1d14453d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDk2NzUsIm5iZiI6MTcyNDc0OTM3NSwicGF0aCI6Ii80MTU1MjE1My8zNjE3MzExODEtNjYwYjI0NDMtNTJiNC00MjM2LWJiNDQtYzExZjFkMTQ0NTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA5MDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZjAzZWY2MzE5YzNlNTU3MmU3OTZiOTE5YmZhNzFkZWZlYjhkM2FjYzAwYmQxMTY3NWM0NDVjZTlmYTk5Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_nePVzKNofEJbKVtRo3-WqVAGQyB3sRRryLcF700iU)

I like the idea of showing the file date in the listing better - trying to sort on anything other than a full date always gets a little weird, because everyone has a slightly different opinion on how it should work.

**Comment by vitalii2011** [comment]
These buttons do not work:
![0010](https://github.com/user-attachments/assets/d345947a-8c91-4073-becd-9387d4a801a5)

**Comment by jtsage** [comment]
Pushing one last RC today, release planned for tonight or tomorrow assuming no stopping bugs are found.
