### ISSUE TITLE
[FEATURE] - Add the ability to back up and restore the Input Bindings file

### ISSUE THREAD

**Issue by ScootersWorkbench** [FSGModding/FSG_Mod_Assistant#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Hey there,  I'm back with another ridiculous request :).
When there are game updates or you have multiple controllers, sometimes the input bindings are reset.   Having the ability to quickly recall (in a controlled way) a previous saved file would be nice.   I travel with a laptop,  so I have different controllers (Farm stick. joysticks and steering wheels) at different locations,  being able to change the config file would be a really nice feature.    
Thanks for your consideration.  Keep up the great work.  This is by far the best Mod Manager ever!
Scooter

**Comment by jtsage** [comment]
yeah.  this has come up a few times.  I would be open to a mostly-manual option.  I've played with trying to automate it, but it's really, really difficult to know when that file changes - and when it does, what the "best" thing is to do with the new version.  But I could see a way to allow you to explicitly tag "known good versions" of the file, and restore as wanted.

**Comment by ScootersWorkbench** [comment]
oh,  I wasn't even thinking of automating it.   Just a way to "name" a version and to have multiple copies that could be selected and "make active".   It's easy to do manually if you know what you're doing,  but having it all part of a "managing application" is really nice.   Plus, it may provide a way to assign buttons outside of the game someday.  :)   I know that file structure is not easy to read when you open the xml,  but you've already figured out many things that I didn't think would be possible.  :)    Anyway,  it's just an idea,  if you want to pursue, that would be cool, if not, no worries.   Thanks for taking the time to look.

**Comment by jtsage** [comment]
haha.  yeah, I looked at it once with a view to messing with it outside the game - I dunno that I'll ever get there, but a save/copy/manage tool is totally possible.  Maybe with a view function too - things get funky with controllers, but I *think* I can pull enough information to make a decent guess at showing what does what

**Comment by jtsage** [comment]
As a side note, wanna send me a couple input binding files if you have kept (it'll make a viewer easier when I get that far)? Either here or in any of the discords we share works - we're both in Vertex, Mods & Links, UMC, and the official one looks like.

**Comment by jtsage** [comment]
![inputManage_overview](https://github.com/user-attachments/assets/8a45aa0a-9b97-4412-b387-05ae8d2dee54)
![inputManage_view](https://github.com/user-attachments/assets/cf31c365-3037-4fdd-b9ce-27299335c9c2)

![inputManage_restore](https://github.com/user-attachments/assets/9e247bde-daeb-415b-aee9-565897c26aed)
![inputManage_delete](https://github.com/user-attachments/assets/ccab6138-b1ae-4447-b60c-8b868f45d7fe)
![inputManage_copy](https://github.com/user-attachments/assets/60718552-c124-44c8-b8ca-a710894537e4)

**Comment by jtsage** [comment]
closing as finished
