### ISSUE TITLE
JSON error[BUG]

### ISSUE THREAD

**Issue by PavementPilot** [FSGModding/FSG_Mod_Assistant#26]
On loading the MMA it does it check of mods then will not load any folders. I have cleared the cache and still have this error

![mma error](https://user-images.githubusercontent.com/3003981/209845346-49f10bda-29e4-4e6c-be51-08f48a5d5b25.png)

 - OS: Windows 11

**Comment by judg393** [comment]
its not just you i have this too 

OS: W10 
[assist.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/10315526/assist.log)
![Screenshot 2022-12-28 172714](https://user-images.githubusercontent.com/55981682/209849977-caa5a769-c260-4e64-b347-c2234830964d.png)
![Screenshot 2022-12-28 172729](https://user-images.githubusercontent.com/55981682/209849978-14aeb32e-bac0-4364-87d5-a7d471fde345.png)


no idea whats happened 0:)

**Comment by jtsage** [comment]
This one is on me, the server those files live on had a space issue, it's been corrected and the data file is rebuilding.  The app should already work again, but the modhub data will be off for the next couple hours while the data file rebuilds.

**Comment by jtsage** [comment]
As a side note, this should probably not cause the whole app to crash, will address.

**Comment by PavementPilot** [comment]
Still not populating my folder list. I will check it a little while. Thanks for addressing this quickly.

**Comment by judg393** [comment]
@jtsage thanks dude still not showing for me but I'll try it tomorrow thank you buddy! Hope you had a good Christmas :)

**Comment by judg393** [comment]
I'm back up and running :)

**Comment by jtsage** [comment]
Aye, fwiw, it will require an app restart. That file is only pulled once at startup. And yeah, good holiday so far. Still enjoying, without most technology until this weekend

**Comment by judg393** [comment]
Enjoy it buddy. Thank you for saving the day again.
