### ISSUE TITLE
inputbinding

### ISSUE THREAD

**Issue by andremeyer123** [FSGModding/FSG_Mod_Assistant#261]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

2024-10-13 17:51:41 |    INFO | input-manager >> Attempting to parse :: H:\Documents\My Games\FarmingSimulator2022\inputBinding.xml
2024-10-13 17:51:41 |  DANGER | render-input >> Unhandled Rejection
2024-10-13 17:51:41 | WARNING | render-input >> Cannot read properties of undefined (reading 'device')
2024-10-13 17:51:41 | WARNING | render-input >> TypeError: Cannot read properties of undefined (reading 'device')
 --     at #parseActionData (file:///C:/Users/,,,/AppData/Local/Programs/fsg-mod-assistant/resources/app.asar/renderer/renderJS/input_ui.js:631:29)
 --     at windowState.initViewer (file:///C:/Users/,,,,/AppData/Local/Programs/fsg-mod-assistant/resources/app.asar/renderer/renderJS/input_ui.js:669:42)
 --     at file:///C:/Users/,,,,,,/AppData/Local/Programs/fsg-mod-assistant/resources/app.asar/renderer/renderJS/input_ui.js:465:67

### Environment

```markdown
- Mod Assistant Version:
- OS:
- Virtualized:
```

**Comment by jtsage** [comment]
ah, damn.  I bet I made the hard assumption the device key would exist, and there is no reason it would have to.  doh.  I'll fix this in the next update, but it might be a few days - messing about with the backend again, maybe trying to leverage some extra processing power with a different language.

**Comment by jtsage** [comment]
closing, this is fixed in upcoming 6.0.0 release

**Comment by andremeyer123** [comment]
closing, this is fixed in upcoming 6.0.0 release ?????  Release  01,2025 ??  schon 2 Monate her 
https://github.com/FSGModding/FSG_Mod_Assistant/issues/278  dieses ist auch sehr Ärgerlich habe es auch.
@jtsage
