### ISSUE TITLE
[FEATURE] Font scale of number of mods on folders

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Hello, I am using 85% scale for the font and everything is ok except for the number displaying the number of mods on the folders in the main window, at this scale it is practically unreadable. Would it be possible to change the ratio for this number or a separate scale parameter?
![image](https://github.com/user-attachments/assets/2157ea1b-8e6c-4ff4-ac0a-d4c6866b8c81)

**Comment by jtsage** [comment]
yep, got it.  It'll be in 6.0.0 as soon as that's actually ready.
