### ISSUE TITLE
[FEATURE] App log

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, if there is a problem with the application, LOG must be selected manually and copied for sharing. In addition, it is not possible to use the shortcut CTRL+A.

### Describe the solution you'd like

Add a button to export LOG to file, or at least a button/shortcut support to select the entire contents of the window.

**Comment by KITT3000** [comment]
MA ;)

**Comment by jtsage** [comment]
added in 5.1.5, closing as complete
