### ISSUE TITLE
[FEATURE] New relase wersion

### ISSUE THREAD

**Issue by criss20ster** [FSGModding/FSG_Mod_Assistant#27]
Hi I have a question for you. Could you convert your mod management program to the one that was under Fs 17/19 called mod manager ? which indicated errors in file descriptions that is xml entries errors in dds storage imiga files and so on ?

**Comment by jtsage** [comment]
For this project, no, probably not - this is really intended for the end user, from a complete new user up to and including the very knowledgeable.

That said, a complete testing suite *is* planned, that will allow you to do a fair bit of what that program did, at least that's the idea.  It's probably several months away, as I've not totally decided what to write it in yet - electron and nodejs is pretty good at doing a lot of things at the same time, less good at some of the sequential things that a test suite would want to do.
