### ISSUE TITLE
[BUG]launch game with custom arguments problem

### ISSUE THREAD

**Issue by Trouble4u56** [FSGModding/FSG_Mod_Assistant#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

wen i start the game with FSgmodassistent i get the following message from steam:
]**launch game with custom arguments 
Farming simulator 25 is attempting to launch with optinal parameters shown below:
""
if you did not request this launch or do not understand these options, select cancel.**

### Steps To Reproduce

when i start FS25 directly from steam, i don't get this message and the game starts correct.
when i start the game from fsgmodassistent then i get the message from steam

i did reinstall fsmodassistent
i did reinstall fs25

i did deleted the gamesettings.xml and restarted fs25 from steam first

did not help

i have a screenshot attacht

### Environment

```markdown
- Mod Assistant Version:5.1.5
- OS:win11
- Virtualized:
-Game version: Steam
```

### Anything else?

![screenshot launch request](https://github.com/user-attachments/assets/0e9387b6-067a-49c5-8e3b-ba6bb5e30dee)

**Comment by jtsage** [comment]
duplicate, #278
