### ISSUE TITLE
[FEATURE] Add Select Overwrite All 

### ISSUE THREAD

**Issue by BattleHook** [FSGModding/FSG_Mod_Assistant#28]
**Is your feature request related to a problem? Please describe.**
When copying a lot of files to another mod collection (e.g. when updating a mod collection I have not played for a while) it takes quite some time to manually select all the Overwrite ticks.

**Describe the solution you'd like**
A button that ticks all the Overwrite yes/no tick-boxes - so Overwrite all duplicate files.

**Describe alternatives you've considered**
Pushing TAB-key and then Space-key repeatedly somewhat speeds up the process, but is still time consuming. No further alternatives I could think of.

**Additional context**
Maybe also make a button for unticking all Overwrite yes/no tick-boxes - so Do not overwrite duplicate files (e.g. when accidentally ticked all files to overwrite) ?

**Comment by jtsage** [comment]
makes sense, yeah. I'll likely add it to the *end* of the list, so you have to really want to do it, along with a clear warning.  But all/none should be pretty easy to add.  I have another small bug from earlier today, so depending on my evening this will hit tonight or in the next few days.

**Comment by jtsage** [comment]
Going to go with a keyboard shortcut instead, and a text bit that lets you know it exists.  This will be in whatever version I'm up to later today.

![2023-01-03 12_35_15-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/210410746-1f96c50c-b988-4b82-bdfe-ba049e1136f2.png)

**Comment by jtsage** [comment]
Included in v1.5.2, out now

**Comment by BattleHook** [comment]
thx a lot 👍
