### ISSUE TITLE
[FEATURE] Find All - Additional Selection Functions

### ISSUE THREAD

**Issue by DanL58** [FSGModding/FSG_Mod_Assistant#29]
Wanted: a way to move/copy mods directly from the Find All window

**Comment by jtsage** [comment]
Thanks, I'll see what makes sense as far as an interface to do this.

**Comment by jtsage** [comment]
So, looking closely at this, it is not in our interest to provide the move/copy functions directly in this window - there are a bunch of reasons for this

1.) Feature skew - if we change how move/copy work in the main window, it would need changed here too
2.) Consistency - right now, you can only move/copy/delete in once place - syncing changes across windows is possible, but it would require re-running the scanner far more often that it is now, slowing down the program over-all

![2023-01-07 17_01_13-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/211172134-3b011ff5-d2c9-4bb1-b656-ecdd5c3e56ef.png)

So, the compromise is this - I've added right click to all of the entries on the find all list that let you select the mod in the main window - and allow you to select the specific version/collection of the mod - it will highlight it, and configure the main window filter to only show that mod (or mods based directly off of it I suppose).  I think this is the best mix of the functionality you were looking for without making the app either more confusing, or leaving things open to breakage.

**Comment by DanL58** [comment]
Sounds good. I didn't realize it would be such a pain, I appreciate your work as well as all the FSG team

**Comment by jtsage** [comment]
No worries.  This will be in the v1.6.0, out later today or tomorrow.
