### ISSUE TITLE
[BUG] Download Mods From Dedicated Server Failing

### ISSUE THREAD

**Issue by Dylan-M** [FSGModding/FSG_Mod_Assistant#30]
**Describe the bug**
When attempting to download mods for my dedicated server, the "Downloading Mods" window just sits there spinning at 0/0 for a long time, and then fails.

**To Reproduce**
1. Set up a mod folder
2. Add the URL: http://---/mods.html for downloading mods from dedicated server
4. Click the download button on the folder list
5. Eventually it will error after a long long wait

**Expected behavior**
Mods will download

**Screenshots**
Screenshots forthcoming when it fails out for me again, I don't currently have the time to wait for it.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - MA Version: 1.5.2 (has been happening since 1.4.1)

**Additional context**
N/A

**Comment by jtsage** [comment]
There are a few issues on my end to correct:

1.) it shouldn't take that long to fail.  It should have gotten an incorrect response pretty quickly from what you set the URL to
2.) the app isn't picky enough when entering a URL, needs some error checking.
3.) there ought to be a cancel button on this too, testing is slow when you have to wait for several GB to download.

That said, try the URL: `http://45.35.207.49:8490/`  - note the lack of mods.html *and* the presence of the trailing slash, both are required.  I just tried your (corrected) URL and it worked.

**Comment by jtsage** [comment]
Added functionality:

1.) if you mis-enter the URL in the details/notes screen, Mod Assistant will warn you
2.) if the mod download fails (as it does with the URL you were using), it will properly show the error now (whoops)
3.) I added a progress bar to all of the loading screens (including the download one)
4.) Progress for downloads is now reported in megabytes instead of bytes - makes it much easier to read.

**Comment by Dylan-M** [comment]
Thanks, both for the info and the quick response. Now, too bad it takes forever to actually download the huge amount of mods I have lol.

**Comment by davarravad** [comment]
@Dylan-M please remove your mods link from your original post.  This is a public thread.

**Comment by Dylan-M** [comment]
> @Dylan-M please remove your mods link from your original post. This is a public thread.

I'm well aware. I'm a GitHub poweruser, and administrator on 3 GH Orgs ;)

The server is public, so I'm not concerned. I'll still remove it, if you'd like.

**Comment by jtsage** [comment]
I obfuscated it, just for posterity.  Closing as complete, the changes will be in v1.6.0, out tonight or tomorrow depending on when our very, very helpful russian friend has a chance to hit crowdin :)
