### ISSUE TITLE
[BREAKING] v1.6.0 will not launch now that newer is available

### ISSUE THREAD

**Issue by Dylan-M** [FSGModding/FSG_Mod_Assistant#33]
**Describe the bug**
When I try and launch the program, it just immediately pops up a crash dialog **behind** the loading dialog. Pulling that out where I can interact with it, and clicking okay, just brings up a further series of error dialogs and eventually exits the program.

**To Reproduce**
1. Have 1.6.0 installed
2. Attempt to launch it
3. See error

**Expected behavior**
Program launches or offers update

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.6.0

**Additional context**
Log file attached
[crash.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/10377752/crash.log)

**Comment by jtsage** [comment]
Crap, I had hoped it was just me.  Fwiw, I installed 1.6.1 over top and that fixed it.  Sorry about that.

**Comment by jtsage** [comment]
I'm going to need some time to hunt down where the actual regression is - it was probably introduced in 1.6.0 - and likely is silently broken in 1.6.1 too.

**Comment by jtsage** [comment]
Fixed in 1.7.1 and tested that the updater works again.  Of course, this is not retroactive, so if you have version 1.6.0 or 1.6.1, you'll need to grab 1.7.1 here: https://github.com/FSGModding/FSG_Mod_Assistant/releases/tag/v1.7.1  

Sorry about that!  Dumb mistakes and all.
