### ISSUE TITLE
Button Texts will not show up since V1.4 or so...

### ISSUE THREAD

**Issue by Kotlett** [FSGModding/FSG_Mod_Assistant#45]
**Describe the bug**
Everytime I start the program OR do any action the button texts will not show up. Please view the attached screenshot:
https://i.ibb.co/r797NSN/Unbenannt.png

If I go then to settings, change the language (for example to english, then german again), the buttons appear again BUT as soon, as I do any action - for example delete a mod or anything else - the buttons "disappear" again.

This behaviour first appeared in V1.4 or so and stayed since then through all updates.

Using Windows 10 x64.

PS: Amazing Tool anyway! ;-)

**Comment by jtsage** [comment]
This is an odd one, and I'm having trouble duplicating. It is almost certainly a timing issue, but I'm having trouble seeing where.

I have a few ideas as to what might be causing this. But, I was hoping you could provide some more info.

1.) Can you paste or screen-cap the output of this page? https://jsfiddle.net/dk12y0L8/1/  - it's a very simple jsFiddle that uses the same code I do to grab the system locale.  If possible, hitting that page in google chrome would be best, but any modern browser should work fine.

2.) Can you send my the `config.json` file in `C:\Users\[YOUR USER NAME]\AppData\Roaming\fsg-mod-assistant` - if you are not familiar with how to get to this folder, you can press `WINDOWS KEY`+`r` and type in `%appdata%` and it'll navigate close to there.

Thanks much!

**Comment by jtsage** [comment]
Still hunting.  If you wanted to be really proactive, there is also a `mod_cache.json` file in that folder, I wouldn't mind a copy of that as well - alas, it is likely too big to dump to github, but if you wanted to upload it somewhere that may be useful too.

**Comment by Kotlett** [comment]
1.) Page output: https://i.ibb.co/M9DKp7w/Unbenannt.png
Nothing special here - gets system language, as it should.....I guess?

2.) config.json (had to zip it because of github):
[config.zip](https://github.com/FSGModding/FSG_Mod_Assistant/files/10445248/config.zip)


**Do you still need the mod_cache?** As far as I can tell, the problem occured unrelated to any specific mods, as I changed them a lot during the days. Currently there are around 700+ or so on my PC (mod cache around 75mb+). I often duplicate whole collection/map folders because I mod myself. ;)

Happy to help! :)

**Comment by jtsage** [comment]
Awseome, both these data bits help a little.  I think if you can, I'd still like to see the mod cache - I managed to sort of duplicate this last night by throwing some really odd characters in the title and author of a fake mod, which I apparently was not sanitizing the data from (I am now).  But there may be more edge cases I missed.

**Comment by Kotlett** [comment]
Ah I get it - so it might have to do with special chars decoding and so on in the mods...?
But interesting then, that the mods themself influence the managers GUI...

Well, anyway, here you go: https://drive.google.com/file/d/15mZpzK0OuDJfKK9HMHmC6IOKPOZhMTOe/view?usp=sharing

Please drop me a line, if you downloaded the file - then I can delete it from my google drive again. :)
thx

**Comment by jtsage** [comment]
> But interesting then, that the mods themself influence the managers GUI...

And that is the heart of the problem I think - they shouldn't be able to :)

**Comment by jtsage** [comment]
Any chance you may have set the "favorite collection" flag on a collection that you no longer have?

You can fix this by doing `WIN KEY+R`, go to `fsg-mod-assistant`, edit `col_notes.json` and remove line with "notes_favorite" on it.  

Or of course you can wait for the version coming out later today that will fix this for you.  Finally did the right set of things to trigger this myself :)

**Comment by jtsage** [comment]
Out of curiosity, any chance you updated to the latest version and this got fixed?  I found a couple things that may have been happening, hope one of those was the problem

**Comment by Kotlett** [comment]
Hey, sorry for the late feedback. I was busy these days and couldn't play at all.

But this: "Any chance you may have set the "favorite collection" flag on a collection that you no longer have?" .... might have been the case.

I will check the new version in the next days and give feedback then. Currently I'm not able to play, sorry. Thanks for your engagement. :)

**Comment by Kotlett** [comment]
GOOD WORK MATE!!!

Problem seems finally solved with the latest version. No more disappearing buttons anymore. Thank you very much! :)

**Comment by jtsage** [comment]
Great, thanks!!
