### ISSUE TITLE
[FEATURE] Enhanced Scroll Bar

### ISSUE THREAD

**Issue by vitalii2011** [FSGModding/FSG_Mod_Assistant#50]
**Screenshots**
![0033](https://user-images.githubusercontent.com/41552153/214924009-dc4f09ac-a4fe-4d44-9ab5-b0c83ea058d5.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Additional context**
https://farming-simulator.com/mod.php?lang=en&country=gb&mod_id=261585

**Comment by jtsage** [comment]
Heh.  you caught me.  I only scrape the modhub website a couple of times a day for that, and I usually concentrate it in the mornings US time to coincide with the usual mod release time.  They were late today - it should correct itself in about an hour (requires app reload)

**Comment by vitalii2011** [comment]
That's pretty much what I thought. But I did not know that the update database is done manually. Sorry to bother you.

**Comment by jtsage** [comment]
No worries.  And it is semi-automated, it's only when they are way late on dropping new mods I sometimes have to give it an extra kick.  It's all in an effort to not constantly spam the modhub web server, as there isn't a public API for this sort of thing, so I am page scraping.

**Comment by vitalii2011** [comment]
Might be time, for promotional purposes, to try downloading FSModAssistant at something like https://www.modhub.us/category/farming-simulator-22-mods (https://www.modhub.us/farming-simulator-22 -mods/fs22-dashboard-v19 ) or https://forbidden-mods.de/filebase/category-file-list/382-filebase-ls22/ ( https://forbidden-mods.de/filebase/file/37659 -quickplay22/ )?

**Comment by vitalii2011** [comment]
On the scroll bar:
![1111](https://user-images.githubusercontent.com/41552153/214961957-7274b697-eecb-4dc4-b809-ff20987bc741.png)

**Comment by jtsage** [comment]
something like this, right?

![2023-01-26 19_49_52-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/214982686-93974b72-ed45-432a-a9ec-0d9dea76e491.png)

**Comment by vitalii2011** [comment]
- Yes.
- Mouse click on the bar became inactive.
The slider is not "cling" to the mouse.

**Comment by vitalii2011** [comment]
With the window expanded to full screen and moving the cursor "outside" the program — the elements of the scroll bar "respond":
https://drive.google.com/file/d/1ufV0_v0nnB9ioXuyV4ZEE47WOzaERKmx/view?usp=share_link

**Comment by vitalii2011** [comment]
P. S. 
The active zone is 1 px near the edge of the window.

**Comment by jtsage** [comment]
Turns out, if you put a DIV overtop of the scrollbar, you can't click on the scrollbar.  Moved it underneath, made the scroll handle see-through, and all good now.  Pushing in a second.

I know it's not totally the place for it, but would you mind shooting me translations for these?  A bit of an addon for the two inspectors I maintain:

```js
<text name="setting_simpleInspector_SolidUnit"       text="Unit of measure: Solids" />
<text name="toolTip_simpleInspector_SolidUnit"       text="Use this unit of measure to display solid products" />
<text name="setting_simpleInspector_LiquidUnit"      text="Unit of measure: Liquids" />
<text name="toolTip_simpleInspector_LiquidUnit"      text="Use this unit of measure to display liquid products" />
```

And two others, that don't have a real name yet in the XML

- Volume
- Weight

Context for both is a type of a unit of measure, i.e Liter is a measure of Volume, Kilogram is a measure of weight

**Comment by vitalii2011** [comment]
```
<text name="setting_simpleInspector_SolidUnit"       text="Ед. измер. тв./сыпучих продуктов" />
<text name="toolTip_simpleInspector_SolidUnit"       text="Использовать эту единицу измерения для твёрдых/сыпучих продуктов" />
<text name="setting_simpleInspector_LiquidUnit"      text="Ед. измерения жидкостей" />
<text name="toolTip_simpleInspector_LiquidUnit"      text="Использовать эту единицу измерения для жидкостей" />
``` 

```
<text name="setting_simpleInspector_Volume"       text="Ед. измерения объёма" />
<text name="toolTip_simpleInspector_Volume"       text="Использовать эту единицу измерения для объёма" />
<text name="setting_simpleInspector_Weight"      text="Ед. измерения массы" />
<text name="toolTip_simpleInspector_Weight"      text="Использовать эту единицу измерения для массы" />
```

**Comment by jtsage** [comment]
You are awesome, thank you!

**Comment by vitalii2011** [comment]
Please. You can always count on my humble help. I will try to do everything for you that circumstances permit.
