### ISSUE TITLE
[BUG] Incorrect detection of "crosplay" mods

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#51]
I have the map 'Ostseeküste 22' in the crossplay version but the program claims that I have the "PC only" version although the link redirects to the correct version.

PC only: https://www.farming-simulator.com/mod.php?mod_id=259109
Crossplay: https://www.farming-simulator.com/mod.php?mod_id=260397
![image](https://user-images.githubusercontent.com/2678653/214948901-042b055b-5609-42ce-926e-42e0ac1537c0.png)

EDIT:
I noticed that in the description of the mod it appears that it contains 1 script, which is not true.

**Comment by jtsage** [comment]
Hmm.  I do love a "this one is not like the others" - thanks!

![2023-01-26 16_11_48-data](https://user-images.githubusercontent.com/605986/214951462-46f69d8c-a549-4588-b5db-e7367ae19200.png)

FWIW, the script *is* there, it is obviously unreferenced in the crossplay version. (as it happens, that's a GE script anyway).  But the scanner is pretty simplistic - "if it has a LUA file, it must be a script mod".  And of course none of the public (or probably private) test scripts will find this, as it's not used anywhere, and LUA is an acceptable file type to be in the mod.

Let me think a bit about the best way to handle this - I probably *can* do some extra testing to see if it's used, but that will come at a speed cost - how much of one is sort of hard to predict before I get into it.

**Comment by KITT3000** [comment]
heh, however, the program is better at searching than I am, it correctly detected what it was supposed to detect, strange that Giants let it through on MH xD

**Comment by jtsage** [comment]
FWIW, in a *slighly* past planning stage we have a tester in the works.  My dream would be that it does all that this does, just a bit more verbosely, all that the scripts here can do: https://github.com/jtsage/FS_XMLTools, and at least *most* of what testrunner does (there are some implications to duplicating the shader cache bit - one is I'm not fully sure how they get GE to spit it out, two is that the list of cache hits is probably proprietary data even if I do know how to retrieve it)
