### ISSUE TITLE
[BUG] Phantom window remains when clicking "Yes" to update prompt

### ISSUE THREAD

**Issue by dskaggs** [FSGModding/FSG_Mod_Assistant#52]
**Describe the bug**
When I launch mod assistant and there is a new version available, I get a phantom window that is unable to be closed that remains after the updater runs. Once the updater is finished, the normal mod assistant window loads and I have 2 windows.

**To Reproduce**
1. Open FSG FS22 Mod Assistant
2. Click Yes on prompt asking if you'd like to install the new version
3. Updater window launches, updates program, and relaunches program
4. Observe "shell" window remains and is unable to be closed 

**Expected behavior**
Initial window fully closes, updater runs, and the new version opens in a normal window.

**Screenshots**
![mod-assistant-phantom-window](https://user-images.githubusercontent.com/432500/215220229-b0f60489-297e-4b67-a6bb-26a6f9fa6fdd.png)

**Desktop (please complete the following information):**
 - OS: Edition	
Windows 11 Pro
Version	22H2
OS build	22621.1105
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Additional context**
Any window that I drag over the affected area is still able to be interacted with. So even though the phantom window appears to be on top of the active window, it does not prevent interacting with the active window. I've observed this on at least the last 2 upgrade notifications (possibly 3). The only way I've found to remove the phantom window is to do a complete PC restart.

**Comment by jtsage** [comment]
Ooh.  This sounds like a good one.  Thanks for the report, I'll see if I can duplicate it and figure out what's going on.

FWIW, you might be able to force kill the old process - it'll be in the task manager as either `FSModAssistant` or `fsg-mod-assistant` or lastly perhaps some version of `electron` - a phantom like that would likely not show as an "App" anymore and be down in "Background Processes"

Nice wallpaper by the way, that's spiffy.

**Comment by dskaggs** [comment]
Yeah, I like Corvettes :)

I killed the `FSModAssistant` but that killed my running "good" version of the app without affecting the phantom window. No mention of either `fsg-mod-assistant` or `electron` in the Background Processes section

**Comment by jtsage** [comment]
Hmm. gross.  My guess is one of the windows is slow to close maybe.  I'm adding some explicit checks to deal with that.  

The *huge* downside to this will be that you won't know if it works for at least 2 versions - the next update will hopefully correct it, but that new code can't run until the update after that.  It might be worth, for the time being, telling the program you want to update "later", then manually exit and restart the application. (in this case "later" means "when I close the program")

**Comment by dskaggs** [comment]
Thanks for the quick look into this. I'll be sure to use the "later" method on this update and then monitor the next update after that and see if the issue persists.

**Comment by dskaggs** [comment]
Followup on this: I just got the update is available notification. As requested, I chose "Later" and hit the X button to close the window. I got the phantom frame again. I can't tell you what version of Mod Assistant I was on before because when I relaunched it, it's now running v2.0.

I'll keep an eye out the next time an upgrade drops and see if the behavior goes away.

**Comment by jtsage** [comment]
That's so weird.  But thank you for keeping me up to date.  You'll likely get another shot at it tonight or early tomorrow, as there are a number of tiny bugs in 2.0.0 that I want to push a fix for.

**Comment by dskaggs** [comment]
Launched version v2.0.0 this morning and the upgrade alert dialog popped up. I clicked "Restart" on the dialog and it closed completely with no phantom windows, upgraded, and restarted v2.0.1 successfully. Thanks a bunch for the fix!
