### ISSUE TITLE
Log file location

### ISSUE THREAD

**Issue by ScootersWorkbench** [FSGModding/FSG_Mod_Assistant#59]
After the 1.10.2 update,  the process mods screen will not complete and closes the application.   I have no error message popup so I'm wondering if there is a log file location that I can see what actually happened and if it's a mod that causes or something else that I should report.

**Comment by jtsage** [comment]
Yes, there is.  `WIN+R`, "%appdata", go to `fsg-mod-assistant`, the file you are looking for is "assist.log"

![2023-01-29 15_17_26-fsg-mod-assistant](https://user-images.githubusercontent.com/605986/215353550-eed69766-a1bc-4ca2-8df7-24fa3e571221.png)

**Comment by ScootersWorkbench** [comment]
Rejection Timestamp : 2023-01-28T20:23:05.973Z

Caught rejection: Error: EPERM: operation not permitted, open 'C:\Users\scota\AppData\Local\fsg-mod-assistant-updater\pending\temp-FSModAssistant-Setup-1.10.2.exe'

Rejection origin: [object Promise]










Error: EPERM: operation not permitted, open 'C:\Users\scota\AppData\Local\fsg-mod-assistant-updater\pending\temp-FSModAssistant-Setup-1.10.2.exe'Exception Timestamp : 2023-01-28T20:25:58.440Z

Caught exception: Error: Tray is destroyed

Exception origin: uncaughtException

Error: Tray is destroyed
    at Timeout._onTimeout (C:\Users\scota\AppData\Local\Programs\fsg-mod-assistant\resources\app.asar\modAssist_main.js:431:29)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)


That was my crash.log file.   I didn't find anything in the assist.log file.

**Comment by jtsage** [comment]
Well, the second part was simple, I've correct that.  The first part is more difficult, I have no idea why that file would be throwing a permission error, it looks like maybe windows got confused in some way?  I'd give deleting that file a shot:

`C:\Users\scota\AppData\Local\fsg-mod-assistant-updater\pending\temp-FSModAssistant-Setup-1.10.2.exe`

I've found one or two open issues on the electron github that hint at this, but nothing terribly helpful.
