### ISSUE TITLE
Is it possible to show the ~icon that the mod's key combination is used in other mods/scripts?

### ISSUE THREAD

**Issue by vitalii2011** [FSGModding/FSG_Mod_Assistant#6]
**Is your feature request related to a problem? Please describe.**

- Now you can understand that the assigned key combination "repeated = conflicts" is possible only when some function does not start / stops working. If it is not displayed in the Help menu (F1) - it is immediately clear that there is a repetition in another mod, and sometimes it is displayed, but does not work. If repeated combinations are already in the keyboard shortcut settings, then you can find out with which particular "intersection" mod only by trying to reassign the already used combination and only then it is shown where it is already used.

**Describe the solution you'd like**

- An icon in a utility or mod for a game with information about conflicting combinations.

**Describe alternatives you've considered**

- For a more or less convenient search for conflicts in inputBinding.xml, I use https://ef7q5.csb.app/ https://codesandbox.io/s/ef7q5

**Additional context**

**Comment by vitalii2011** [comment]
P. S.
To avoid creating a new issue: "cross" or "erase".
![0010](https://user-images.githubusercontent.com/41552153/199527800-77247664-90d2-4985-8a75-4557a20b45d4.png)
![erase](https://user-images.githubusercontent.com/41552153/199527807-a8c0655a-5544-44d2-944d-c8707cab1951.png)
![Hapus_Aplikasi_Pengunci-80x80](https://user-images.githubusercontent.com/41552153/199527808-81898126-8800-4db3-8672-9471e1178f4d.png)

**Comment by jtsage** [comment]
Re: the PS - that one is easy, I'll get that in today.

**Comment by jtsage** [comment]
Re: the original issue - that is an *awesome* idea.  I'm pretty sure I can grab the keybinds from the modDesc, yes.  Comparing them against other mods is going to be somewhat of a challange, but it's probably possible.  But yes, 100%, this is something I want to do.  I'm going to mark this as 1.1.0 as we really want to get a "real" initial release done, but it should come in a week or two I hope.

**Comment by vitalii2011** [comment]
> …

P. P. S.
When scrolling through the list of mods, I would very much like, if not difficult, that the bar with the Search and the very necessary "none" button would not be hidden. Now: select a mod at the top of the list - see information about it - scroll, select another mod and ... the "Find on ModHub" button is not active - scroll (without a scrollbar, (it's good that it's not there - superfluous)) remove all selections - return to middle of the list.

Forgive my laziness to create a new issue. )

**Comment by vitalii2011** [comment]
> Re: the PS - that one is easy, I'll get that in today.

I really liked that the icon only appears in a non-empty search field.

- Portable v0.10.2 updated to desktop v0.10.3 - not very good. Maybe it would be better if a window appeared in the portable with the message: "There is a new version. Open the site for download?"?

**Comment by jtsage** [comment]
> * Portable v0.10.2 updated to desktop v0.10.3 - not very good. Maybe it would be better if a window appeared in the portable with the message: "There is a new version. Open the site for download?"?

Huh.  it's supposed to just quietly fail, I thought.  1.0.0 is being pushed in a few, there is a fix in there that will stop the portable from checking for the update - I'll look into adding a facility to check for the update but not download & apply it in the future.

**Comment by jtsage** [comment]
![2022-11-12 12_29_19-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/201491978-feb3e0cc-1ba2-4f02-9b5e-9c412348f706.png)
![2022-11-12 12_29_38-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/201491979-1456b396-8c77-4f7d-b05b-e6ef86f73871.png)
![2022-11-12 12_29_44-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/201491981-cc321fcd-669f-4e4e-8c4e-4ad20ad98e54.png)
![2022-11-12 14_49_20-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/201492009-85714630-31e6-4a44-b18e-00d186a27a8b.png)
![2022-11-12 14_49_32-FSG FS22 Mod Assistant](https://user-images.githubusercontent.com/605986/201492010-ec733991-910a-4390-b408-1b6420ab2aff.png)

Getting there on 1.1.0 - last thing is the dev controls addition, and then I'll push out a test version.  I went ahead and added all of the (added) keybinds to get developer info at the bottom of the detail screen - I was already needing to read it all, so why not, right?

Of course, this will warn you based on the *default* key bindings, not whatever you may have reset them to.  Reading inputBindings.xml may come later, but it's a little bit harder, as the way this feature currently works, it's only looking for conflict in *each* collection, rather the whole list of what you have (or had, as bindings do not remove themselves when you no longer have a mod)

**Comment by jtsage** [comment]
I'm open to the idea of doing translations for the keys themselves, it's just a *lot* of extra calls, and a fair bit of (mostly) rendundent entries in the language files.  As I am an english only user, I bow to the folks who would know better than me if it's something that would be helpful. (I've seen chinese character keyboards, but honestly have no clue how much localization is done in other parts of the world)

**Comment by vitalii2011** [comment]
> Я открыт для идеи сделать переводы для самих ключей, это просто _ много _ дополнительных вызовов и немало (в основном) избыточных записей в языковых файлах. Поскольку я пользователь только на английском языке, я преклоняюсь перед людьми, которые лучше меня знают, может ли это быть чем-то полезным. (Я видел клавиатуры с китайскими иероглифами, но, честно говоря, понятия не имею, сколько локализации делается в других частях мира)

As for CP specifically, it has localized hotkey names:
![Image 001](https://user-images.githubusercontent.com/41552153/201495053-2f513d20-7217-469d-bb16-f9f23d3517c0.png)
In Easy Development Controls:
![Image 002](https://user-images.githubusercontent.com/41552153/201495193-ab344eb2-e6b1-4e07-9ffe-cbe2e24ece08.png)
But these are exemplary fashions (hehe. The machine always translates "mod"(ru: "мод") from Russian as "fashion"(ru: "мода")), other authors may not adhere to this.
Maybe, if not difficult, add translations of the names of the keyboard shortcut functions for those mods where there are translation files. But in any case, translations of mod shortcuts should be in mods, not in FSModAssistant.

**Comment by vitalii2011** [comment]
> Of course, this will warn you based on the _default_ key bindings, not whatever you may have reset them to. Reading inputBindings.xml may come later, but it's a little bit harder, as the way this feature currently works, it's only looking for conflict in _each_ collection, rather the whole list of what you have (or had, as bindings do not remove themselves when you no longer have a mod

It would be nice, but it's understandable. In any case, your program is very useful and convenient.

**Comment by jtsage** [comment]
Sorry, I should have been more clear - when I was talking key translations, I mean the literal key - e.g. "Left SHIFT".  I'm not sure if that is useful or not.  Like I said, I have seen chinese keyboards where those keys were localised (probably, I don't read chinese), but I'm not sure if they typically are in other parts of the world.  As to pulling the translation of the action name from the mod, I decided not to - only because the popular mods like courseplay do it *right*, but not all of them do.  It's also a whole lot more data to dump into the cache, and it's already big enough :)

**Comment by vitalii2011** [comment]
Based on my experience of translating mods of authors from China, Japan and Taiwan, I can assume that "Alt", "Ctrl", etc. they use in texts localized for their countries, i.e. - these names do not need to be translated.
For example, a translation into Russian will look very strange and a "translation clarification" will be required. )
Of course, this is my subjective opinion.

**Comment by jtsage** [comment]
So, I went ahead and went in-game and grabbed the displayed text for each button.  I know I did a good job on the ones that use a latin character set, I *think* I got the russian correct, but I was comparing online translations by eye, and I have zero experience with the Cyrillic character set.

```js
	'ru' : {
		'KEY_pause'               : 'PAUSE',
		'KEY_esc'                 : 'ESC',
		'KEY_space'               : 'ПРОБЕЛ',
		'KEY_delete'              : 'DELETE',
		'KEY_insert'              : 'INSERT',
		'KEY_home'                : 'HOME',
		'KEY_end'                 : 'END',
		'KEY_pageup'              : 'PAGE UP',
		'KEY_pagedown'            : 'PAGE DOWN',

		'KEY_rshift'              : 'ПРАВЫЙ SHIFT',
		'KEY_lshift'              : 'ЛЕВЫЙ SHIFT',
		'KEY_rctrl'               : 'ПРАВЫЙ CTRL',
		'KEY_lctrl'               : 'CTRL',
		'KEY_ralt'                : 'ПРАВЫЙ ALT',
		'KEY_lalt'                : 'ALT',
		
		'MOUSE_BUTTON_LEFT'       : '🖯 ВЛЕВО',
		'MOUSE_BUTTON_MIDDLE'     : '🖯 MIDDLE',
		'MOUSE_BUTTON_RIGHT'      : '🖯 ВПРАВО',
		'MOUSE_BUTTON_WHEEL_UP'   : '🖯 КОЛЁИКО ВВЕРХ',
		'MOUSE_BUTTON_WHEEL_DOWN' : '🖯 КОЛЁИКО ВНИЗ',
	},``` 

If there is a better option for any of these than Giants used, I'm happy to update it.  I did find it interesting that for ALT and CTRL, apparently "Left" is the default, and extra detail is only provided for the "Right" version of them.

**Comment by vitalii2011** [comment]
> ```js
> 		'MOUSE_BUTTON_LEFT'       : '🖯 ВЛЕВО',
> 		'MOUSE_BUTTON_MIDDLE'     : '🖯 MIDDLE',
> 		'MOUSE_BUTTON_RIGHT'      : '🖯 ВПРАВО',
> 		'MOUSE_BUTTON_WHEEL_UP'   : '🖯 КОЛЁИКО ВВЕРХ',
> 		'MOUSE_BUTTON_WHEEL_DOWN' : '🖯 КОЛЁИКО ВНИЗ',
> ```

`		'MOUSE_BUTTON_LEFT'       : 'ЛЕВАЯ КЛАВИША МЫШИ',
		'MOUSE_BUTTON_MIDDLE'     : 'СРЕДНЯЯ КЛАВИША МЫШИ',
		'MOUSE_BUTTON_RIGHT'      : 'ПРАВАЯ КЛАВИША МЫШИ',
		'MOUSE_BUTTON_WHEEL_UP'   : 'КОЛЁСИКО МЫШИ ВВЕРХ',
		'MOUSE_BUTTON_WHEEL_DOWN' : 'КОЛЁСИКО МЫШИ ВНИЗ',` 
- This game is played by people who may not understand what is on the icon, emoticon (?) "computer mouse". Maybe I'm wrong, then - leave it as you have (missing "С" - "КОЛЁ(С)ИКО"), removing the "МЫШИ".
- About mouse keys you can:
`		'MOUSE_BUTTON_LEFT'       : 'ЛКМ',
		'MOUSE_BUTTON_MIDDLE'     : 'СКМ',
		'MOUSE_BUTTON_RIGHT'      : 'ПКМ',` 
These are very well established and used abbreviations, but I saw that they were unknown to some (few) users.
