### ISSUE TITLE
[RELEASE-TRACK] 2.0.0 Bug List & Known Issues (v2.0.1 Changes)

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#62]
Wow, that was fast.  Known bugs in 2.0.0

- [x] folder watchers might not be unbinding correctly (not always reproducible) 2bff688
- [x] drag-and-drop file _from_ app breaks subsequent drops _to_ app. 6bcbc3d
- [x] app fails to start if fs22 log not found #63 / log not opening 1ff39c2 26bfb33
- [x] language selection fails e2a5325
- [x] clicking on taskbar icon minimizes app to tray rather than taskbar 882d09e 9394d66
- [x] footer display can go to two lines and look ugly. f3edec4
- [x] keys tag can appear in both green and red. ee27bc9 4fb5d33

**Comment by vitalii2011** [comment]
- 1. The language of the program does not switch in Settings;
- 2. Failed to add/view log:

https://user-images.githubusercontent.com/41552153/216294965-4e3ad122-3ab3-4402-bced-f86c70b9f2e9.mp4

**Comment by vitalii2011** [comment]
Unusual (not very convenient) behavior of the program when clicking on the tray icon:

https://user-images.githubusercontent.com/41552153/216295996-31ad539c-b17a-45ff-b996-299ba5e20b1d.mp4

Maybe this is better?:

https://user-images.githubusercontent.com/41552153/216296204-2915d63c-05c0-47d8-b8bc-bdc662d72b0f.mp4

**Comment by KITT3000** [comment]
I confirm, on version 2.0.0 it is not possible to change the language.

**Comment by jtsage** [comment]
> -2. Failed to add/view log:

I think I found the issue here - I am trying to avoid adding a specific setting for this, but there was a very shaky assumption in my code, so, I'd like to try out my fix in 2.0.1 (later today due to the language select but moving the timetable way up), and if it still doesn't function the debug log should be more useful (footer button)  Thanks!

**Comment by jtsage** [comment]
> Unusual (not very convenient) behavior of the program when clicking on the tray icon:

Maybe something like this for the title bar (only messed with the main screen, I think the sub-windows are fine as-is, as they don't hide anyway).

![2023-02-02 13_44_51-main html - FSG_Mod_Assistant - Visual Studio Code](https://user-images.githubusercontent.com/605986/216420710-03ce97a8-a56c-4dec-b27b-1a4ad8f81595.png)

**Comment by jtsage** [comment]
[v2.0.1](https://github.com/FSGModding/FSG_Mod_Assistant/releases/tag/v2.0.1) Pushed Live.  Should fix all of these, I hope.

**Comment by vitalii2011** [comment]
> [v2.0.1 Опубликовано в ](https://github.com/FSGModding/FSG_Mod_Assistant/releases/tag/v2.0.1) прямом эфире. Я надеюсь, что все это должно быть исправлено.

Thanks for all the fixes!
