### ISSUE TITLE
[BUG] Starting App in Parallels Running Windows 11

### ISSUE THREAD

**Issue by iammichaelgarcia** [FSGModding/FSG_Mod_Assistant#63]
The app won't start up.  Uncaught rejection - quitting

Caught rejection: Error: no such file or directory, watch 'C:\Users\{USERNAME}\log.txt'

Origin: [object Promise]

**To Reproduce**
1. Start Parallels Version 18.1.1 (53328)
2. Open FSModAssistant-..any version of 2.0
3. See error.

**Desktop (please complete the following information):**
 - OS: Windows 11 running in Parallels v.18.1.1 (53328)
![Screenshot 2023-02-02 at 12 00 02 AM](https://user-images.githubusercontent.com/32854344/216267148-77332d7f-cb13-4b29-a9dc-ddba07ac6d0c.jpg)

**Comment by jtsage** [comment]
Added to list. Probably a bug fix mid-day will be released

**Comment by iammichaelgarcia** [comment]
> This should be corrected in 2.0.1, if it's not, please let me know.

That was quick!  Nice work.  No errors on startup.

**Comment by jtsage** [comment]
Excellent, thanks!
