### ISSUE TITLE
Adding a Collection Description is not allowed.

### ISSUE THREAD

**Issue by ScootersWorkbench** [FSGModding/FSG_Mod_Assistant#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to add a "Collection Description" for the "Edit Folder Details", adding any character into the box changes to Red Circled Explanation Point and doesn't allow the description to be entered.  

![image](https://user-images.githubusercontent.com/75384460/216838246-6d9dd85c-8925-469e-a9c9-86fc1957d2a6.png)

### Expected Behavior

I was thinking that this would give me a Description Line and would show along with the Folder Name.   I'm not the best at naming folders and sometimes the Folder names do not make sense with the Collection.  :) 

### Environment

```markdown
- Mod Assistant Version:  2.0.1
- OS:  Win10
- Virtualized: No
```

**Comment by jtsage** [comment]
Does it still allow you to type?  Admittedly, the context clue here is less than clear - what it's supposed to be indicating is that the value is unsaved - blurring (moving out of) the box after typing should set it back to green.  

A better idea might be that yellow/orange color for unsaved - there are only "real" conditions on a couple of those fields related to length.

https://user-images.githubusercontent.com/605986/216838988-bdf49dc3-a7b2-4011-a568-f9101ff80019.mp4

**Comment by ScootersWorkbench** [comment]
Ok,  so we can put that one on an error between the keyboard and the chair.   Yes,  If you change focus to another box, the text is saved.  :)    It works as expected.

**Comment by jtsage** [comment]
Great.  yeah, I'll modify that context to be a little more intuitive.  Re also #65
