### ISSUE TITLE
[BUG] The "minimize, maximize, close" buttons cover the tooltip

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For "Activate" the tooltip is displayed at the top and is covered by these window buttons, but for "Deactivate" it is already displayed below and is easily visible.
![image](https://user-images.githubusercontent.com/2678653/218167927-b6bd5920-d9c8-462d-b6b9-26a98a73567a.png)

### Environment

```markdown
- Mod Assistant Version: 2.0.9
- OS: Win10 22H2
- Virtualized: No
```

**Comment by jtsage** [comment]
Got it.  I hadn't been forcing the placement on those anywhere, I am now.

**Comment by jtsage** [comment]
closing as complete.
