### ISSUE TITLE
[FEATURE] Can I activate multiple folders at a time?

### ISSUE THREAD

**Issue by VeezyLife** [FSGModding/FSG_Mod_Assistant#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Is there a way I can activate more than just one mod folder at a time?

### Describe the solution you'd like

If there isnt, then this would be great to have the ability to do and really help organization with anyone who has ALOT of mods installed. Making different folders only to be able to use 1 makes for redundant copies of the same mods that i want to use in separate groups.

**Comment by jtsage** [comment]
The short answer is no.  Farming Simulator just can't read more than one folder at a time - the only way to actually do this would be:

1.) Creating a temporary folder on "set active" will your selections in it - it'd be yet another copy of the mods.

2.) Utilizing symLinks to do basically the same, but they don't take up disk space - unfortunately, as in #24, Mod Assistant can't create symLinks without running itself as administrator, and that's not a road I want to travel down.
