### ISSUE TITLE
[Translation] Wrong definition in german

### ISSUE THREAD

**Issue by DerMudder** [FSGModding/FSG_Mod_Assistant#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a small translation error in translations/de.json 
The translation "Schlüssel" is wrong. "Schlüssel" is the thing to open locks. "Tasten" are the things on the keyboard.
```
	"mod_badge_keys_ok": "Schlüssel",
	"mod_badge_keys_bad": "Schlüssel",
	"detail_key_binds": "Schlüsselbindungen",
```

### Expected Behavior

```
	"mod_badge_keys_ok": "Tasten",
	"mod_badge_keys_bad": "Tasten",
	"detail_key_binds": "Tastenbelegungen",
```

### Environment

```markdown
- Mod Assistant Version:
- OS:
- Virtualized:
```

**Comment by jtsage** [comment]
Thanks, I'll get this in the next release.
