### ISSUE TITLE
[BUG] ModHub List is inaccurate

### ISSUE THREAD

**Issue by ScootersWorkbench** [FSGModding/FSG_Mod_Assistant#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a folder that is only Modhub mods but many are registering as non-Modhub.   It's not a high priority,  just wanted you to be aware.

![image](https://user-images.githubusercontent.com/75384460/219461040-69f02bff-41f2-4287-94ec-dc2da5b98902.png)

### Environment

```markdown
- Mod Assistant Version:
- OS:
- Virtualized:
```

**Comment by jtsage** [comment]
At this point, I'm not sure if my list-maker fell off the rails or something else went wrong, but I too have noticed this.  Thanks, I will investigate.

**Comment by jtsage** [comment]
I finally remembered to do this, should be sorted now.  You will need to fully exit / re-enter Mod Assistant to update the list (it does it once on open)

The only possible downside is I did prune those things that were on modhub and have been recalled/removed for whatever reason.
