### ISSUE TITLE
Version 2.1.1

### ISSUE THREAD

**Issue by Farmer17** [FSGModding/FSG_Mod_Assistant#87]
# Known Bugs - v Will copy and move one file at a time into mod file but not multiple files and will let you check the box (overwrite) but will not work. It will work if it is a brand-new mod map and its empty, but not with mods currently in there.

This issue is an umbrella issue to keep track of bugs in the current version.  You can reply directly here, but opening a new issue would make life easier for us.

## Issue List
 -

**Comment by jtsage** [comment]
Mentioned in #77 and #82, corrected with 6923dc1 - This will be fixed when the next version drops in the next day or two.

**Comment by Farmer17** [comment]
Thankyou
Got the update yesterday. This is is the best mod management ever. Great
job.
