### ISSUE TITLE
[VERSION TRACK] 2.2.0 Known Issues & Bugs

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#88]
# Known Bugs - v2.2.0

This issue is an umbrella issue to keep track of bugs in the current version.  You can reply directly here, but opening a new issue would make life easier for us.

## Issue List

- [ ] Mis-aligned text/buttons in interfaces other than english
- [x] Copy/Move to an empty destination crashed the app
- [x] Copy favorites doesn't work in multi-version mode

**Comment by vitalii2011** [comment]
![Image 001](https://user-images.githubusercontent.com/41552153/230017846-04dc180b-86c9-4578-a390-a3fe5b99bbb5.png)
![Image 002](https://user-images.githubusercontent.com/41552153/230017851-28ba8d04-a609-4e3a-87d3-1f3ee164a308.png)
![Image 003](https://user-images.githubusercontent.com/41552153/230017859-76df78ae-e1fd-49a2-803a-f2eeec7e4296.png)
![Image 004](https://user-images.githubusercontent.com/41552153/230017863-042e009d-694a-40e1-904d-85a15464f75c.png)
![Image 005](https://user-images.githubusercontent.com/41552153/230017867-65f47709-0a28-4ad2-89f2-c0ce2c0ef336.png)
![Image 006](https://user-images.githubusercontent.com/41552153/230017869-cb0f682d-a594-498f-a240-bfa800358346.png)
![Image 007](https://user-images.githubusercontent.com/41552153/230017873-98449cdb-2ac3-4f2b-b4e5-48029903a1ce.png)

**Comment by jtsage** [comment]
Fwiw, totally forgot to check here when I was doing today's version.  Been a very busy time at work, I'll hit the display issues soon.

**Comment by vitalii2011** [comment]
Is it forgotten?

**Comment by jtsage** [comment]
It was not - but it looks like my fix didn't work if the window is not the "default" size or larger.  I'll do some more tweaking
