### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Black131313** [FSGModding/FSG_Mod_Assistant#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Привет! Манеджер не добавляет fs19 не появляется кнопка.

### Environment

```markdown
- Mod Assistant Version:
- OS:
- Virtualized:
```

**Comment by KITT3000** [comment]
Have you enabled multiple FS support mode? Everything works fine for me.
