### ISSUE TITLE
[BUG] Mod is not identified as ModHub Ressource

### ISSUE THREAD

**Issue by urbanswelt** [FSGModding/FSG_Mod_Assistant#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The MOD FS22 MAN TGS HKL was tagged as nonModHub
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=264716&title=fs2022

### Expected Behavior

I would have expected it to exist as a Modhub link

### Steps To Reproduce

1. Download the Mod and copy it in the MOD folder
2. Open FSG Mod Assistant
3. check the tag

### Environment

```markdown
- Mod Assistant Version:2.1.2
- OS:Windows 11 pro
- Virtualized:No
```

### Anything else?

Other Mod`s from this Team are ok:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/2138928/222951060-eba46561-ad8b-4837-b5b8-3f050dc6bb33.png">

**Comment by jtsage** [comment]
Mmmhmm.  Need to re-run the mass import again, or maybe figure out why it's not getting updated a bit more than daily like it should.  I know it missed a couple more this week too.  Thanks
