### ISSUE TITLE
[FEATURE] Top-Layer Button for individual Websites

### ISSUE THREAD

**Issue by Kotlett** [FSGModding/FSG_Mod_Assistant#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The possibility to enter custom links per mod is great, but to open them for a quick peek is inconvenient. You have to do multiple left- and rightclicks to "scroll" through your mod repository and check them for updates.

### Describe the solution you'd like

I would love a simple "button" appear, as soon as you enter a custom link. Just exactly like the "View on ModHub" Button. So you can check every mod with two simple clicks: select the mod, push the button to the right. Done.

Otherwise / currently you have to select the mod, right click it, "search" for the line in the dropdown menu, left click it and THEN it opens the url. Seems not a big deal, but it really sums up in big collections. :(

**Comment by jtsage** [comment]
OK, added.
![2023-04-04 21_21_06-FSG Mod Assistant](https://user-images.githubusercontent.com/605986/229957105-0e6356ee-d9b1-4b1e-a284-59c37ac1c36f.png)

**Comment by jtsage** [comment]
I had originally planned to replace the modhub button with the "source website" one, but there are cases where a mod has both (as pictured)

**Comment by Kotlett** [comment]
> I had originally planned to replace the modhub button with the "source website" one, but there are cases where a mod has both (as pictured)

That was exactly my idea too. Thought, you can't simply replace mod hub button, but maybe only show an additional button, if the source is set.
BUT that will mess up the design, as you then have mods with and without "open source buttons", resulting in a constant number of buttons change.

So i would just add the open source button for all mods and simply grey it out on mods without open source. Exactly like the mod hub button itself.

Thanks for the improvement, that will come handy!
