### ISSUE TITLE
[FEATURE] New Listing / sorting for version compare dialogue

### ISSUE THREAD

**Issue by Kotlett** [FSGModding/FSG_Mod_Assistant#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

If you open the version compare dialogue, the collections listed as plain text without paragraphes, wich makes it really hard to compare (see example here: https://ibb.co/rmC619r )

### Describe the solution you'd like

I would suggest to add simple paragraphs to the listing, which will it make much easier to read and compare them.

For example - instead of:

"FS22_REA Wheels
Collections: FS22_Italia_Emilia_Ext: 1.1.1.0. FS22_Ostseeküste: 1.1.1.0, FS22_Midwesthorizon: 1.1.0.0, FS22_Uppermissippi: 1.1.1.0, FS22_NDH_New_year_Version: 1.1.1.0, FS22_Rennebu: 1.1.1.0" [...]

just make it look like this:

```
FS22_REA Wheels
Collections: 
FS22_Italia_Emilia_Ext: 1.1.1.0. 
FS22_Ostseeküste: 1.1.1.0, 
FS22_Midwesthorizon: 1.1.0.0, 
FS22_Uppermissippi: 1.1.1.0, 
FS22_NDH_New_year_Version: 1.1.1.0, 
FS22_Rennebu: 1.1.1.0
...
```

### Anything else?

By the way; just love your tool and just want to help improve it - it's no nagging at all. ;-)
Already the best FS-Tool, ever created!

**Comment by jtsage** [comment]
![2023-04-04 20_45_59-FSG Mod Assistant](https://user-images.githubusercontent.com/605986/229953283-802d84b3-780b-496f-af4e-6483fc75b3a5.png)

I met you halfway.  Those that have a difference are show in a list format, the ones that are the same are just comma seperated like before.

**Comment by Kotlett** [comment]
That's even better! Great, thanks!
